# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""

BBLAYERS ?= " \
  /home/brighton/STAR/star-yocto/poky/meta \
  /home/brighton/STAR/star-yocto/poky/meta-poky \
  /home/brighton/STAR/star-yocto/poky/meta-yocto-bsp \
  /home/brighton/STAR/star-yocto/meta-raspberrypi \
  /home/brighton/STAR/star-yocto/meta-openembedded/meta-oe \
  /home/brighton/STAR/star-yocto/meta-openembedded/meta-python \
  /home/brighton/STAR/star-yocto/meta-openembedded/meta-networking \
  /home/brighton/STAR/star-yocto/meta-openembedded/meta-multimedia \
  /home/brighton/STAR/star-yocto/meta-ros/meta-ros-common \
  /home/brighton/STAR/star-yocto/meta-ros/meta-ros2 \
  /home/brighton/STAR/star-yocto/meta-ros/meta-ros2-jazzy \
  /home/brighton/STAR/star-yocto/meta-star \
  "
