
services:
  yocto-builder:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-1000}
        GROUP_ID: ${GROUP_ID:-1000}
    container_name: tda4vm-yocto-builder
    hostname: tda4vm-builder
    volumes:
      # Mount the entire yocto directory
      - .:/home/yocto/yocto-workspace
      # Persistent cache for downloads and sstate
      - yocto-downloads:/home/yocto/yocto-workspace/downloads
      - yocto-sstate:/home/yocto/yocto-workspace/sstate-cache
      # Persistent build tmp directory (optional, can be large)
      # - yocto-tmp:/home/yocto/yocto-workspace/build/arago-tmp-external-arm-glibc
    environment:
      # Pass through host environment variables
      - MACHINE=j721e-evm
      - DISTRO=arago
      # Build parallelization (adjust based on your system)
      - BB_NUMBER_THREADS=${BB_NUMBER_THREADS:-8}
      - PARALLEL_MAKE=${PARALLEL_MAKE:-8}
      # Git configuration
      - GIT_USER_NAME=${GIT_USER_NAME:-"Developer"}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-"developer@example.com"}
    working_dir: /home/yocto/yocto-workspace
    stdin_open: true
    tty: true
    # Resource limits (adjust based on your system)
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 8G
    # Uncomment for network debugging
    # network_mode: host

volumes:
  yocto-downloads:
    name: tda4vm-yocto-downloads
  yocto-sstate:
    name: tda4vm-yocto-sstate
  # Uncomment if you want to persist tmp directory
  # yocto-tmp:
  #   name: tda4vm-yocto-tmp