// SPDX-License-Identifier: MIT
/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 
 * @copyright Copyright (c) 2026 Locked Inc.
*/

#include <stdint.h>

/* Cortex-M7 Coprocessor Access Control Register */
#define CPACR ((volatile uint32_t*)0xE000ED88U)

/* Enable FPU full access (CP10 and CP11) before the C runtime uses it */
void SystemInit(void)
{
    *CPACR |= ((3UL << 20U) | (3UL << 22U));
    __asm volatile("dsb");
    __asm volatile("isb");
}

int main(void)
{
    /* Loop forever */
    for (;;)
        ;
}
