---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    commit: "a7f6c3e67bd9170e93b2b94676e84018faf0df91"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://git.ti.com/git/ti-sdk-linux/meta-tisdk.git"
    branch: "kirkstone"
    commit: "09.01.00.08"

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "kirkstone"
    commit: "09.01.00.008"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-demos:
      meta-arago-test:

  meta-qt5:
    url: "https://github.com/meta-qt5/meta-qt5.git"
    branch: "kirkstone"
    commit: "ae8a97f79364bed1abc297636f7933d0e35f22be"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "kirkstone"
    commit: "67b0ef4256a484851f3556d281ca4caa88374388"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "kirkstone"
    commit: "8a75c61cce2aa1d6e5a3597ab8fc5a7e6aeae1e4"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "kirkstone"
    commit: "09.01.00.008"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "kirkstone"
    commit: "b187fb9232ca0a6b5f8f90b4715958546fc41d73"
    layers:
      meta-arm:
      meta-arm-toolchain:

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "kirkstone"
    commit: "11da43b58e19583a9bc16044309610cfb2e86469"
    layers:
      meta:

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "kirkstone"
    commit: "87d730d9c1778c7f892b096878f338f36d6877f4"
