---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "139f61fe9eec221745184a14b3618d2dfa650b91"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://github.com/TexasInstruments/meta-tisdk.git"
    branch: "scarthgap"
    commit: "11.01.05.03"
    layers:
      meta-ti-foundational:
      meta-ti-ml:

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "11.01.05"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"
    commit: "18bda8b8a5cf03ad16ed3c52b110b63b98b8ed77"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "9e040ee8dd6025558ea60ac9db60c41bfeddf221"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "727811eaf256b88fd135be99559f2cbf14c82fce"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: "https://git.yoctoproject.org/meta-lts-mixins"
    branch: "scarthgap/rust"
    commit: "a8046d5ec53b1856169ac795aa87cb0d5db84c04"

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "11.01.05"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "8e0f8af90fefb03f08cd2228cde7a89902a6b37c"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "eea5ec23155cfd47781599fdc9a92c21e4caffc8"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "cfa97a50e06fb0fcc7cbc0ada54ce7ad5ba29ebe"
    layers:
      meta:
