---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "6c2641f7a9e92c1b82e306f59ddd3c1249c52cbf"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://github.com/TexasInstruments/meta-tisdk.git"
    branch: "scarthgap"
    commit: "10.01.10.04"

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "10.01.10"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-demos:
      meta-arago-test:

  meta-qt5:
    url: "https://github.com/meta-qt5/meta-qt5.git"
    branch: "scarthgap"
    commit: "eb828418264a49b8d00035cb3d7b12fcea3be801"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "450941a1b6df96285691e8c23d4f332d3c88a994"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "b8d1a14f7f3b76457c36752202ea7ae5881b6654"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "10.01.10"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "7088279c0ab00c7dabefdd4544951b4746b48476"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "9fbfa9db33131abdf3870a94f00199eb53e276e5"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "dac630ab5ee7aa6c5c7c294093adbd11b116c765"
    layers:
      meta:
