---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "696c2c1ef095f8b11c7d2eff36fae50f58c62e5e"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://github.com/TexasInstruments/meta-tisdk.git"
    branch: "scarthgap"
    commit: "11.00.09.04"
    layers:
      meta-ti-foundational:
      meta-ti-ml:

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "11.00.09"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-browser:
    url: "https://github.com/OSSystems/meta-browser.git"
    branch: "master"
    commit: "68e8cbf51ac46c8c1b3923ee2b20e27ba9d3faa4"
    layers:
      meta-chromium:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"
    commit: "78855ecc613fcd6eff1a5a012cab5e679df329e4"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "0c191912421adff2f753e470056a9a525fbce760"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "edd1a1e284fdcb80cd48d411f235d47f23bc27ae"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "11.00.09"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "3cadb81ffaa9f03b92e302843cb22a9cd41df34b"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "b9ef02282197380ef05edbd0eb852e1934ceb59b"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "1be6d83466e3a0da4222ba502c2a86c25c835a35"
    layers:
      meta:
