---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.0"
    commit: "40fd5f4eef7460ca67f32cfce8e229e67e1ff607"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://git.ti.com/git/ti-sdk-linux/meta-tisdk.git"
    branch: "kirkstone"
    commit: "09.02.01.10"

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "kirkstone"
    commit: "09.02.00.010"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-demos:
      meta-arago-test:

  meta-browser:
    url: "https://github.com/OSSystems/meta-browser.git"
    branch: "master"
    commit: "d3d16b47e17dc899e5298cff698dc32e5e639ab4"
    layers:
      meta-chromium:

  meta-qt5:
    url: "https://github.com/meta-qt5/meta-qt5.git"
    branch: "kirkstone"
    commit: "644ebf220245bdc06e7696ccc90acc97a0dd2566"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "kirkstone"
    commit: "8f0eb65edaf6d280294c33446a9bb073a50b8c14"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "kirkstone"
    commit: "5a6f7925bd2b885955c942573f70a5594f231563"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "kirkstone"
    commit: "09.02.00.010"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "kirkstone"
    commit: "260e3adc2bf322f52d81c0642c825088a88bb051"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "kirkstone-clang12"
    commit: "c2e89dc7e1dfcc1bbe432afca2dc43d6560cb007"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "kirkstone"
    commit: "8a502301209ef144932ef5071c1a9b738db23270"
    layers:
      meta:

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "kirkstone"
    commit: "fdb683aa69d4d70aca17c2d53be3f900ae9d5e72"
