---
header:
  version: 17
  includes:
    - ./templates/bblayers.conf.yml
    - ./templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap-wip"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: "https://git.yoctoproject.org/meta-lts-mixins"
    branch: "scarthgap/rust"
    commit: "a8046d5ec53b1856169ac795aa87cb0d5db84c04"

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap-wip"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    layers:
      meta:
