---
header:
  version: 17
  includes:
    - ./templates/bblayers.conf.yml
    - ./templates/local-arago64-v3.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "master"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "master-next"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "dev"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "master"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "master"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "master-next"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "master"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "master"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "master"
    layers:
      meta:

local_conf_header:
  oe-layersetup-local-conf-config-specific: |
    OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
