---
header:
  version: 17
  includes:
    - ./templates/bblayers.conf.yml
    - ./templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap-next"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: "https://git.yoctoproject.org/meta-lts-mixins"
    branch: "scarthgap/rust"
    commit: "a8046d5ec53b1856169ac795aa87cb0d5db84c04"

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap-next"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    layers:
      meta:

local_conf_header:
  oe-layersetup-local-conf-config-specific: |
    OVERRIDES:append = ":recipe-${@os.path.basename(d.getVar('FILE'))}"
    BRANCH:recipe-ltp-ddt_20250130.bb = "cicd"
    BRANCH:recipe-cadence-mhdp-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-cnm-wave-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-goodix-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-linux-ti-staging_6.12.bb = "ti-linux-6.12.y-cicd"
    BRANCH_ARM64:recipe-linux-ti-staging-rt_6.12.bb = "ti-linux-6.12.y-cicd"
    BRANCH_ARM32:recipe-linux-ti-staging-rt_6.12.bb = "ti-rt-linux-6.12.y-arm32-cicd"
    BRANCH:recipe-prueth-fw_5.6.15.bb = "ti-linux-firmware-next"
    BRANCH:recipe-pruhsr-fw_2.17.25.bb = "ti-linux-firmware-next"
    BRANCH:recipe-pruprp-fw_2.17.25.bb = "ti-linux-firmware-next"
    BRANCH:recipe-prusw-fw_3.2.9.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-dac-fw.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-dm-fw.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-eth-fw.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-hsm-demo-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-pka-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-rtos-echo-test-fw.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-rtos-messageq-test-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-ti-sci-fw_git.bb = "ti-linux-firmware-next"
    BRANCH:recipe-u-boot-ti-staging_2025.01.bb = "ti-u-boot-2025.01-next"
    BRANCH:recipe-vxd-dec-fw_git.bb = "ti-linux-firmware-next"
