---
header:
  version: 17
  includes:
    - ./templates/bblayers.conf.yml
    - ./templates/local-v3.conf.yml

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "master"
    layers:
      .: disabled

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "master"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "master"
    layers:
      meta-arm:
      meta-arm-toolchain:

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "master"
    layers:
      meta:
