---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "86e7a58c0e9904c33b1b94dddc3d683c2da22d1a"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "11.01.08"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"
    commit: "559e316dc5facf962ed06e3ac5dd2ecc20a4ae5b"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "151273b120117468e70733020b6db864d8180c0b"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "e8fd97d86af86cdcc5a6eb3f301cbaf6a2084943"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: "https://git.yoctoproject.org/meta-lts-mixins"
    branch: "scarthgap/rust"
    commit: "65c51abe3871d50e599366765838d1478eba093e"

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "11.01.08"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "8e0f8af90fefb03f08cd2228cde7a89902a6b37c"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "aef850f7fa53121c74b244b7ae40d31fb9809ccf"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "c374e6cfcdd2c8ba17d82ffcfdeb97d21144e2bf"
    layers:
      meta:
