# Robot Gateway Bridge Configuration
# Configuration file for the bridge between Java Gateway and ROS2 robot system

# Gateway connection settings
gateway_url: "http://localhost:8080"
bridge_port: 9090

# ZMQ communication settings
ros2_zmq_address: "tcp://localhost:5555"  # Send commands to ROS2
ros2_sub_address: "tcp://localhost:5556"  # Receive data from ROS2

# Robot configuration
robot:
  name: "pynq_robot"
  type: "autonomous_rover"
  max_linear_velocity: 2.0   # m/s
  max_angular_velocity: 1.0  # rad/s
  
  # Safety limits
  emergency_stop_enabled: true
  collision_detection: true
  max_acceleration: 1.0  # m/s²

# Sensor configuration
sensors:
  lidar:
    enabled: true
    topic: "/scan"
    update_rate: 10.0  # Hz
    
  stereo_camera:
    enabled: true
    left_topic: "/stereo/left/image_raw"
    right_topic: "/stereo/right/image_raw"
    update_rate: 30.0  # Hz
    
  imu:
    enabled: true
    topic: "/imu/data"
    update_rate: 100.0  # Hz

# Navigation configuration
navigation:
  enabled: true
  global_planner: "NavfnPlanner"
  local_planner: "DWBLocalPlanner"
  
  # Costmap parameters
  costmap:
    global_frame: "map"
    robot_base_frame: "base_link"
    update_frequency: 5.0
    publish_frequency: 2.0
    
  # Recovery behaviors
  recovery_behaviors:
    - "clear_costmap_recovery"
    - "rotate_recovery"
    - "backup_recovery"

# SLAM configuration
slam:
  enabled: true
  algorithm: "slam_toolbox"  # or "cartographer"
  
  # Map parameters
  map:
    resolution: 0.05  # m/pixel
    width: 2000       # pixels
    height: 2000      # pixels
    
  # SLAM parameters
  scan_topic: "/scan"
  odom_topic: "/odom"
  map_frame: "map"
  odom_frame: "odom"
  base_frame: "base_link"

# Communication settings
communication:
  # Data forwarding rates (Hz)
  pose_update_rate: 10.0
  sensor_data_rate: 5.0
  status_update_rate: 1.0
  
  # Queue sizes
  command_queue_size: 100
  data_queue_size: 1000
  
  # Timeouts (seconds)
  gateway_timeout: 5.0
  ros2_timeout: 2.0

# Logging configuration
logging:
  level: "INFO"  # DEBUG, INFO, WARNING, ERROR
  file: "/var/log/robot-gateway-bridge.log"
  max_size: "10MB"
  backup_count: 5
  
  # Log categories
  categories:
    bridge: "INFO"
    ros2: "INFO"
    sensors: "WARNING"
    navigation: "INFO"

# Performance tuning
performance:
  # Thread settings
  worker_threads: 4
  io_threads: 2
  
  # Buffer sizes
  zmq_send_buffer: 1048576    # 1MB
  zmq_receive_buffer: 1048576 # 1MB
  
  # Message batching
  batch_size: 10
  batch_timeout: 0.1  # seconds

# Development settings
development:
  debug_mode: false
  simulate_robot: false
  mock_sensors: false
  
  # Test endpoints
  test_commands: true
  health_check_interval: 30.0  # seconds

# Security settings
security:
  enable_authentication: false
  api_key: ""
  allowed_ips: []
  
  # Rate limiting
  max_requests_per_minute: 1000
  max_commands_per_minute: 100