---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "f40a3a477d5241b697bf2fb030dd804c1ff5839f"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "b6349e47760397add572cc27468e0f30b40474c1"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-demos:
      meta-arago-test:

  meta-qt5:
    url: "https://github.com/meta-qt5/meta-qt5.git"
    branch: "scarthgap"
    commit: "a1af9bdf2bcf06df85aeac997bfbdcb414d8e0e0"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "450941a1b6df96285691e8c23d4f332d3c88a994"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "b8d1a14f7f3b76457c36752202ea7ae5881b6654"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "f06324bc1649e4f437686560cbd66f973ba920f5"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "7088279c0ab00c7dabefdd4544951b4746b48476"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "9fbfa9db33131abdf3870a94f00199eb53e276e5"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "92cb4641ff4ec8c1f681bca21cfeaf2ba6923ab7"
    layers:
      meta:

  meta-tisdk:
    url: "https://git.ti.com/git/ti-sdk-linux/meta-tisdk.git"
    branch: "scarthgap"
    commit: "fcd7661087b0dd5b5b57d30ba0d45f2698e962f8"

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "scarthgap"
    commit: "41499d7bcc8d37862b93c0d56cf782f9182d0be1"
