---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "86e7a58c0e9904c33b1b94dddc3d683c2da22d1a"
    layers:
      .: disabled

  meta-tisdk:
    url: "https://github.com/TexasInstruments/meta-tisdk.git"
    branch: "scarthgap"
    commit: "11.01.07.05"
    layers:
      meta-ti-foundational:

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "11.01.07"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-selinux:
    url: "https://git.yoctoproject.org/meta-selinux"
    branch: "scarthgap"
    commit: "30a49ab1298d2a081089a9e4c760a9e02f8100f6"

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"
    commit: "2b4e60e319348ae2d53072b901645f30b4cc42bf"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "a5449c0c50aa07d02186f548fe6bb6c1ce8823dc"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "e8fd97d86af86cdcc5a6eb3f301cbaf6a2084943"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-lts-mixins:
    url: "https://git.yoctoproject.org/meta-lts-mixins"
    branch: "scarthgap/rust"
    commit: "a8046d5ec53b1856169ac795aa87cb0d5db84c04"

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "11.01.07"
    layers:
      meta-ti-extras:
      meta-beagle:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "8e0f8af90fefb03f08cd2228cde7a89902a6b37c"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "aef850f7fa53121c74b244b7ae40d31fb9809ccf"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "24c0ab18045920bb5c1e965c0ea6d176fd6de234"
    layers:
      meta:

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "scarthgap"
    commit: "11.01.07.05"

local_conf_header:
  oe-layersetup-local-conf-config-specific: |
    DISTRO_FEATURES:append = " acl xattr pam selinux"
