---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "696c2c1ef095f8b11c7d2eff36fae50f58c62e5e"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "c04e85dd207dd24387edac10526b9ec971df9496"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-test:

  meta-qt6:
    url: "https://code.qt.io/yocto/meta-qt6.git"
    branch: "6.9"
    commit: "fce7cf8c3aa54b3650a30a79dce705838c32f3c3"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "9e040ee8dd6025558ea60ac9db60c41bfeddf221"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "e92d0173a80ea7592c866618ef5293203c50544c"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "a98a2e1029870b25e117d4c9410e75bfd955f35a"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "8e0f8af90fefb03f08cd2228cde7a89902a6b37c"
    layers:
      meta-arm:
      meta-arm-toolchain:

  meta-clang:
    url: "https://github.com/kraj/meta-clang"
    branch: "scarthgap"
    commit: "eaa08939eaec9f620b14742ff3ac568553683034"

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "b214cc84a922f7a3fb7ebbc501189ce25e8bd2bd"
    layers:
      meta:

  meta-tisdk:
    url: "https://git.ti.com/git/ti-sdk-linux/meta-tisdk.git"
    branch: "scarthgap"
    commit: "1f96dccc01f10c73295e0bac6a15a97d3d4562fd"
    layers:
      meta-ti-foundational:

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "scarthgap"
    commit: "81d1b80b2a314814c6d900e82ea2da93eee3f57d"
