---
header:
  version: 17
  includes:
    - ../templates/bblayers.conf.yml
    - ../templates/local-arago64-v2.conf.yml

target: tisdk-default-image

repos:
  bitbake:
    url: "https://git.openembedded.org/bitbake"
    branch: "2.8"
    commit: "11d83170922a2c6b9db1f6e8c23e533526984b2c"
    layers:
      .: disabled

  meta-arago:
    url: "https://git.yoctoproject.org/meta-arago"
    branch: "scarthgap"
    commit: "cbf054c7401af6e1e8bcc4eab07daa9a4996f7f3"
    layers:
      meta-arago-distro:
      meta-arago-extras:
      meta-arago-demos:
      meta-arago-test:

  meta-qt5:
    url: "https://github.com/meta-qt5/meta-qt5.git"
    branch: "scarthgap"
    commit: "eb828418264a49b8d00035cb3d7b12fcea3be801"

  meta-virtualization:
    url: "https://git.yoctoproject.org/meta-virtualization"
    branch: "scarthgap"
    commit: "54b806b1985f3989722ee308e1073530fe3328c1"

  meta-openembedded:
    url: "https://git.openembedded.org/meta-openembedded"
    branch: "scarthgap"
    commit: "80e01188fa822d87d301ee71973c462d7a865493"
    layers:
      meta-networking:
      meta-python:
      meta-oe:
      meta-gnome:
      meta-filesystems:
      meta-multimedia:

  meta-ti:
    url: "https://git.yoctoproject.org/meta-ti"
    branch: "scarthgap"
    commit: "84328ead40d7e6fcce4d80ab7d07f4dcaf9d777e"
    layers:
      meta-ti-extras:
      meta-ti-bsp:

  meta-arm:
    url: "https://git.yoctoproject.org/meta-arm"
    branch: "scarthgap"
    commit: "ecece16871afe6b674d2aafd27e0f18bbaef1966"
    layers:
      meta-arm:
      meta-arm-toolchain:

  oe-core:
    url: "https://git.openembedded.org/openembedded-core"
    branch: "scarthgap"
    commit: "bf3fe8c01c5cc00ada22049f4f0abb485e2a626f"
    layers:
      meta:

  meta-tisdk:
    url: "https://git.ti.com/git/ti-sdk-linux/meta-tisdk.git"
    branch: "scarthgap"
    commit: "af81e0d81c5efd005bfc0ef749f690f9748c70f6"

  meta-edgeai:
    url: "https://git.ti.com/git/edgeai/meta-edgeai.git"
    branch: "scarthgap"
    commit: "a3b8006957fbc31f8375a5989be7c42b2ba2959b"
