#!/bin/bash
# Setup pip cache directory for faster PYNQ image builds
# This creates a persistent cache for Python packages

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}pip Cache Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}ERROR: Do not run this script as root!${NC}"
    echo "Run it as a regular user."
    exit 1
fi

# Default cache directory
PIP_CACHE_DIR="${HOME}/.cache/pynq-build/pip"

echo -e "${YELLOW}Setting up pip cache directory...${NC}"
echo ""

# Check if cache directory already exists
if [ -d "$PIP_CACHE_DIR" ]; then
    CACHE_SIZE=$(du -sh "$PIP_CACHE_DIR" 2>/dev/null | cut -f1 || echo "0B")
    echo -e "${YELLOW}Cache directory already exists:${NC}"
    echo "  Location: $PIP_CACHE_DIR"
    echo "  Size:     $CACHE_SIZE"
    echo ""

    echo -e "${YELLOW}Do you want to clear the existing cache?${NC}"
    read -p "(y/n) " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$PIP_CACHE_DIR"
        echo -e "${GREEN}✓${NC} Cache cleared"
    else
        echo -e "${YELLOW}Keeping existing cache${NC}"
    fi
fi

# Create cache directory
mkdir -p "$PIP_CACHE_DIR"
echo -e "${GREEN}✓${NC} Cache directory created: $PIP_CACHE_DIR"
echo ""

# Copy existing pre-built wheels if they exist
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PREBUILT_WHEELS="$SCRIPT_DIR/PYNQ/sdbuild/packages/python_packages_jammy/pre-built/root/.cache/pip/wheels"

if [ -d "$PREBUILT_WHEELS" ]; then
    echo -e "${YELLOW}Copying pre-built wheels to cache...${NC}"
    mkdir -p "$PIP_CACHE_DIR/wheels"
    cp -rf "$PREBUILT_WHEELS"/* "$PIP_CACHE_DIR/wheels/" 2>/dev/null || true
    WHEEL_COUNT=$(find "$PIP_CACHE_DIR/wheels" -name "*.whl" 2>/dev/null | wc -l)
    echo -e "${GREEN}✓${NC} Copied $WHEEL_COUNT pre-built wheels"
    echo ""
fi

# Create a configuration file for the build system
CONFIG_FILE="$SCRIPT_DIR/.pip-cache-config"
cat > "$CONFIG_FILE" <<EOF
# pip cache configuration for PYNQ builds
# Generated by setup-pip-cache.sh on $(date)
PIP_CACHE_DIR=$PIP_CACHE_DIR
EOF

echo -e "${GREEN}✓${NC} Configuration saved: $CONFIG_FILE"
echo ""

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

echo -e "${YELLOW}Cache Configuration:${NC}"
echo "  Location: $PIP_CACHE_DIR"
echo ""

CURRENT_SIZE=$(du -sh "$PIP_CACHE_DIR" 2>/dev/null | cut -f1 || echo "0B")
echo "  Current size: $CURRENT_SIZE"
echo ""

echo -e "${GREEN}Benefits:${NC}"
echo "  • Packages downloaded once, reused across builds"
echo "  • Significantly faster pip install operations"
echo "  • Reduces network bandwidth usage"
echo "  • Works alongside apt-cacher-ng"
echo ""

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run your build - it will populate the cache"
echo "     ./build.sh"
echo ""
echo "  2. Subsequent builds will use cached packages"
echo "     (First build downloads, later builds reuse)"
echo ""

echo -e "${YELLOW}Cache Management:${NC}"
echo "  • View cache size:"
echo "    du -sh $PIP_CACHE_DIR"
echo ""
echo "  • Clear cache:"
echo "    rm -rf $PIP_CACHE_DIR"
echo "    (then run this script again)"
echo ""
echo "  • Cache location is stored in:"
echo "    .pip-cache-config"
echo ""
