#!/bin/bash
# Setup git reference cache for faster PYNQ image builds
# This creates a local mirror of frequently cloned repositories

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}========================================${NC}"
echo -e "${BLUE}Git Cache Setup${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

# Check if running as root
if [ "$EUID" -eq 0 ]; then
    echo -e "${RED}ERROR: Do not run this script as root!${NC}"
    echo "Run it as a regular user."
    exit 1
fi

# Default cache directory
GIT_CACHE_DIR="${HOME}/.cache/pynq-build/git"

echo -e "${YELLOW}Setting up git cache directory...${NC}"
echo ""

# Check if cache directory already exists
if [ -d "$GIT_CACHE_DIR" ]; then
    CACHE_SIZE=$(du -sh "$GIT_CACHE_DIR" 2>/dev/null | cut -f1 || echo "0B")
    REPO_COUNT=$(find "$GIT_CACHE_DIR" -name "config" -path "*/refs/*" -prune -o -type f -name "config" -print 2>/dev/null | wc -l)
    echo -e "${YELLOW}Cache directory already exists:${NC}"
    echo "  Location:     $GIT_CACHE_DIR"
    echo "  Size:         $CACHE_SIZE"
    echo "  Repositories: $REPO_COUNT"
    echo ""

    echo -e "${YELLOW}Do you want to clear the existing cache?${NC}"
    read -p "(y/n) " -n 1 -r
    echo ""

    if [[ $REPLY =~ ^[Yy]$ ]]; then
        rm -rf "$GIT_CACHE_DIR"
        echo -e "${GREEN}✓${NC} Cache cleared"
    else
        echo -e "${YELLOW}Keeping existing cache${NC}"
    fi
fi

# Create cache directory
mkdir -p "$GIT_CACHE_DIR"
echo -e "${GREEN}✓${NC} Cache directory created: $GIT_CACHE_DIR"
echo ""

# Create a configuration file for the build system
SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
CONFIG_FILE="$SCRIPT_DIR/.git-cache-config"
cat > "$CONFIG_FILE" <<EOF
# Git cache configuration for PYNQ builds
# Generated by setup-git-cache.sh on $(date)
GIT_CACHE_DIR=$GIT_CACHE_DIR
EOF

echo -e "${GREEN}✓${NC} Configuration saved: $CONFIG_FILE"
echo ""

# Optional: Pre-populate cache with known repositories
echo -e "${YELLOW}Do you want to pre-populate the cache with common repositories?${NC}"
echo "This will clone several repositories (may take 10-15 minutes)."
echo "You can skip this and let the cache populate during builds."
read -p "Pre-populate cache? (y/n) " -n 1 -r
echo ""
echo ""

if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo -e "${YELLOW}Pre-populating cache...${NC}"
    echo ""

    # Function to create a reference clone
    create_reference() {
        local url=$1
        local name=$2

        echo -e "${YELLOW}Caching: $name${NC}"
        echo "  URL: $url"

        # Create a safe directory name from the URL
        local cache_name=$(echo "$url" | sed 's|https\?://||' | sed 's|/|_|g' | sed 's|\.git$||')
        local cache_path="$GIT_CACHE_DIR/$cache_name"

        if [ -d "$cache_path" ]; then
            echo "  Already cached, updating..."
            (cd "$cache_path" && git fetch --all --prune) || true
        else
            git clone --mirror "$url" "$cache_path" || {
                echo -e "${RED}  Failed to clone $name${NC}"
                return 1
            }
        fi
        echo -e "${GREEN}✓${NC} Cached"
        echo ""
    }

    # Add repositories that are cloned DURING the build process here
    # Note: PYNQ itself doesn't need to be cached since it's already a submodule

    # Cache XRT which is cloned during the build
    create_reference "https://github.com/Xilinx/XRT.git" "Xilinx XRT"

    # Add more build-time dependencies here as discovered
    # create_reference "https://github.com/some/dependency.git" "Build dependency"

    echo -e "${GREEN}✓${NC} Cache pre-population complete"
    echo ""
fi

echo -e "${BLUE}========================================${NC}"
echo -e "${GREEN}✓ Setup Complete!${NC}"
echo -e "${BLUE}========================================${NC}"
echo ""

echo -e "${YELLOW}Cache Configuration:${NC}"
echo "  Location: $GIT_CACHE_DIR"
echo ""

CURRENT_SIZE=$(du -sh "$GIT_CACHE_DIR" 2>/dev/null | cut -f1 || echo "0B")
echo "  Current size: $CURRENT_SIZE"
echo ""

echo -e "${GREEN}How It Works:${NC}"
echo "  Git will use the cache as a reference when cloning repositories."
echo "  This works using git's --reference flag."
echo ""
echo "  Benefits:"
echo "  • Repositories cloned once, objects shared across builds"
echo "  • Significantly faster git clone operations"
echo "  • Reduces network bandwidth usage"
echo "  • Automatic object deduplication"
echo ""

echo -e "${YELLOW}Next steps:${NC}"
echo "  1. Run your build - it will use the git cache"
echo "     ./build.sh"
echo ""
echo "  2. The build system will automatically:"
echo "     - Check if repositories exist in cache"
echo "     - Use --reference flag when cloning"
echo "     - Update cache with new commits"
echo ""

echo -e "${YELLOW}Cache Management:${NC}"
echo "  • View cache size:"
echo "    du -sh $GIT_CACHE_DIR"
echo ""
echo "  • Update cached repositories:"
echo "    for repo in $GIT_CACHE_DIR/*; do"
echo "      (cd \$repo && git fetch --all --prune)"
echo "    done"
echo ""
echo "  • Clear cache:"
echo "    rm -rf $GIT_CACHE_DIR"
echo "    (then run this script again)"
echo ""
echo "  • List cached repositories:"
echo "    ls -lh $GIT_CACHE_DIR"
echo ""

echo -e "${YELLOW}Advanced Usage:${NC}"
echo "  The cache can be used manually with git:"
echo "    git clone --reference $GIT_CACHE_DIR/repo_name URL"
echo ""
echo "  Or set globally:"
echo "    git config --global clone.referenceIfAble true"
echo ""
