# esp32-firmware/components/star_bus/CMakeLists.txt

idf_component_register(
  SRCS
    "star_bus_types.c"
    "star_bus_manager.c"
    "star_bus_config.c"
    "star_bus_i2c.c"
    "star_bus_spi.c"
    "star_bus_spi_peripheral.c"
    "star_bus_smbus.c"
    "star_bus_smbus_peripheral.c"
    "star_bus_async.c"
    "star_bus_batch.c"
    "star_bus_stats.c"
    "star_bus_i2c_peripheral.c"
    "star_bus_onewire.c"
    "star_bus_onewire_peripheral.c"
    "star_bus_uart.c"
    "star_bus_helpers.c"
    "star_bus_devices.c"
    "star_bus_debug.c"
  INCLUDE_DIRS
    "include"
  REQUIRES
    driver
    esp_common
    esp_timer
    freertos
    star_pin_validator
    star_error_handler
)
