#!/usr/bin/env python3
"""
Analyze example dependencies and generate lib_deps for platformio.ini

This script scans all example .c files in the examples/ directory,
identifies which STAR libraries they include, and generates the
appropriate lib_deps declarations for each example environment.
"""

import os
import re
from pathlib import Path
from collections import defaultdict

# Map from include patterns to library names
LIBRARY_MAP = {
    'star_sensor_mpu6050': 'lib/star_sensor_mpu6050',
    'star_sensor_dht22': 'lib/star_sensor_dht22',
    'star_sensor_bh1750': 'lib/star_sensor_bh1750',
    'star_sensor_hcsr04': 'lib/star_sensor_hcsr04',
    'star_sensor_qmc5883l': 'lib/star_sensor_qmc5883l',
    'star_sensor_mq135': 'lib/star_sensor_mq135',
    'star_sensor_gps6mv2': 'lib/star_sensor_gps6mv2',
    'star_sensor_rplidar_c1': 'lib/star_sensor_rplidar_c1',
    'star_sensor_pca9685': 'lib/star_sensor_pca9685',
    'star_sensor_bno055_bmp280': 'lib/star_sensor_bno055_bmp280',
    'star_sensor_sick_tim561': 'lib/star_sensor_sick_tim561',
    'star_module_a7670g': 'lib/star_module_a7670g',
    'star_camera_imx219': 'lib/star_camera_imx219',
    'star_bms_bq7850': 'lib/star_bms_bq7850',
}

def analyze_example_file(file_path):
    """
    Analyze a single example file and extract library dependencies.

    Args:
        file_path: Path to the example .c file

    Returns:
        Set of library dependencies (e.g., {'lib/star_sensor_mpu6050', ...})
    """
    deps = set()

    try:
        with open(file_path, 'r', encoding='utf-8') as f:
            content = f.read()

        # Find all #include "..." and #include <...> statements
        includes = re.findall(r'#include\s+[<"]([^>"]+)[>"]', content)

        for include in includes:
            # Check if this include matches any known library
            for lib_pattern, lib_name in LIBRARY_MAP.items():
                if lib_pattern in include:
                    deps.add(lib_name)

    except Exception as e:
        print(f"Error reading {file_path}: {e}")

    return deps

def analyze_all_examples(examples_dir):
    """
    Analyze all example files in the examples directory.

    Args:
        examples_dir: Path to examples directory

    Returns:
        Dict mapping example names to their dependencies
    """
    examples_dir = Path(examples_dir)
    results = {}

    for example_file in sorted(examples_dir.glob('*.c')):
        example_name = example_file.stem  # Filename without extension
        deps = analyze_example_file(example_file)

        if deps:
            results[example_name] = sorted(deps)

    return results

def generate_platformio_config(example_deps):
    """
    Generate platformio.ini configuration snippets for examples with dependencies.

    Args:
        example_deps: Dict mapping example names to their dependencies

    Returns:
        String containing platformio.ini configuration
    """
    output = []
    output.append("; ============================================")
    output.append("; Example Library Dependencies")
    output.append("; Auto-generated by scripts/analyze_example_deps.py")
    output.append("; ============================================\n")

    for example_name, deps in example_deps.items():
        if not deps:
            continue

        output.append(f"; {example_name} needs: {', '.join(deps)}")
        output.append(f"[env:example_{example_name}]")
        output.append(f"extends = env:esp32_wroom")
        output.append(f"lib_deps =")
        output.append(f"    ${{env:esp32_wroom.lib_deps}}  ; Inherit core deps")
        for dep in deps:
            output.append(f"    {dep}")
        output.append(f"board_build.cmake_extra_args =")
        output.append(f"    -DSTAR_EXAMPLE_SRC=examples/{example_name}.c")
        output.append("")

    return '\n'.join(output)

def main():
    """Main entry point."""
    script_dir = Path(__file__).parent
    project_root = script_dir.parent
    examples_dir = project_root / 'examples'

    if not examples_dir.exists():
        print(f"Error: Examples directory not found: {examples_dir}")
        return 1

    print(f"Analyzing examples in: {examples_dir}")
    print("-" * 80)

    example_deps = analyze_all_examples(examples_dir)

    print(f"\nFound {len(example_deps)} examples with library dependencies:\n")

    for example_name, deps in sorted(example_deps.items()):
        print(f"{example_name:40} -> {', '.join([d.split('/')[-1] for d in deps])}")

    print("\n" + "=" * 80)
    print("Generating platformio.ini configuration snippets...")
    print("=" * 80 + "\n")

    config = generate_platformio_config(example_deps)

    # Save to file
    output_file = project_root / 'scripts' / 'example_deps_config.ini'
    with open(output_file, 'w', encoding='utf-8') as f:
        f.write(config)

    print(f"Configuration saved to: {output_file}")
    print(f"\nTo use this configuration:")
    print(f"  1. Review the generated file")
    print(f"  2. Manually merge appropriate sections into platformio.ini")
    print(f"  3. Test building examples to verify dependencies")

    return 0

if __name__ == '__main__':
    exit(main())
