//! Doxygen XML parser modules.
//!
//! Parses the XML output generated by `doxygen` (with `GENERATE_XML = YES`)
//! into Rust data structures suitable for Typst emission.

pub mod compound;
pub mod description;
pub mod graph;
pub mod index;
pub mod linkedtext;
pub mod memberdef;

pub use compound::CompoundKind;
pub use index::parse_index;
