(part "SSW-106-02-G-S-RA"
    (packageRef "SSW-106-XX-YYY-S-RA")
    (interface
        (port "1" (symbPinId 1) (portName "1") (portType INOUT))
        (port "2" (symbPinId 2) (portName "2") (portType INOUT))
        (port "3" (symbPinId 3) (portName "3") (portType INOUT))
        (port "4" (symbPinId 4) (portName "4") (portType INOUT))
        (port "5" (symbPinId 5) (portName "5") (portType INOUT))
        (port "6" (symbPinId 6) (portName "6") (portType INOUT))
    )
    (partClass UNDEF)
    (useInSchema Y)
    (useInLayout Y)
    (inPartsList Y)
    (partType NORMAL)
    (placeRestriction FREE)
    (property "compKind" "181")
    (property "Mouser_Part_Number" "200-SSW10602GSRA")
    (property "Mouser_Price/Stock" "https://www.mouser.co.uk/ProductDetail/Samtec/SSW-106-02-G-S-RA?qs=92ilVni64gxK1gPeghtn8A%3D%3D")
    (property "Manufacturer_Name" "SAMTEC")
    (property "Manufacturer_Part_Number" "SSW-106-02-G-S-RA")
    (property "Description" ".100" Tiger Buy Socket Strip,  positions per row,  row")
    (property "Datasheet_Link" "http://suddendocs.samtec.com/prints/ssw-1xx-xx-xxx-x-xx-xxx-xx-mkt.pdf")
    (property "symbolName1" "SSW-106-02-G-S-RA")
)
