/*
* Copyright (c) 2016 - 2025 Renesas Electronics Corporation and/or its affiliates
*
* SPDX-License-Identifier: BSD-3-Clause
*/
/***********************************************************************************************************************
*  File Name    : fucku.c
*  Description  : Main Program
*  Creation Date: 2026-02-07
*  This file was generated by Smart Configurator.
***********************************************************************************************************************/
#include "r_smc_entry.h"

void main(void);

void main(void)
{

}