// STAR Documentation Template
// Auto-generated by star-docs -- do not edit manually

// Page setup
#set page(
  paper: "us-letter",
  margin: (top: 1in, bottom: 1in, left: 1in, right: 1in),
  header: context {
    let page-num = counter(page).get().first()
    if page-num > 1 [
      #set text(8pt, fill: rgb("#666666"))
      #h(1fr) STAR - Simultaneous Tracking and Robotics #sym.dash.em v1.0.0
    ]
  },
  footer: context {
    let page-num = counter(page).get().first()
    if page-num > 1 [
      #set text(8pt, fill: rgb("#666666"))
      #h(1fr) #counter(page).display("1 / 1", both: true)
    ]
  },
)

// Font configuration
#set text(font: "New Computer Modern", size: 10pt)
#show raw: set text(font: "DejaVu Sans Mono", size: 8.5pt)

// Heading styles
#set heading(numbering: "1.1.1")
#show heading.where(level: 1): it => {
  pagebreak(weak: true)
  block(width: 100%)[
    #set text(18pt, weight: "bold", fill: rgb("#1565c0"))
    #it
    #v(4pt)
    #line(length: 100%, stroke: 0.5pt + rgb("#1565c0"))
  ]
}

#show heading.where(level: 2): it => {
  block(width: 100%)[
    #set text(14pt, weight: "bold", fill: rgb("#1976d2"))
    #it
  ]
}

#show heading.where(level: 3): it => {
  block(width: 100%)[
    #set text(12pt, weight: "bold", fill: rgb("#1e88e5"))
    #it
  ]
}

// Paragraph spacing
#set par(leading: 0.65em, first-line-indent: 0pt)
#show par: set block(spacing: 0.65em)

// Link styling
#show link: it => {
  set text(fill: rgb("#1565c0"))
  underline(it)
}

// Code block styling
#show raw.where(block: true): it => {
  block(
    width: 100%,
    fill: rgb("#f5f5f5"),
    stroke: 0.5pt + rgb("#e0e0e0"),
    inset: 8pt,
    radius: 3pt,
    it,
  )
}

// Custom functions for documentation blocks
#let doc-note(body) = block(
  width: 100%,
  fill: rgb("#e3f2fd"),
  stroke: (left: 3pt + rgb("#1565c0")),
  inset: 8pt,
  radius: (right: 3pt),
  [*Note:* #body],
)

#let doc-warning(body) = block(
  width: 100%,
  fill: rgb("#fff3e0"),
  stroke: (left: 3pt + rgb("#e65100")),
  inset: 8pt,
  radius: (right: 3pt),
  [*Warning:* #body],
)

#let doc-precondition(body) = block(
  width: 100%,
  fill: rgb("#e8f5e9"),
  stroke: (left: 3pt + rgb("#2e7d32")),
  inset: 8pt,
  radius: (right: 3pt),
  [*Pre:* #body],
)

#let doc-postcondition(body) = block(
  width: 100%,
  fill: rgb("#f3e5f5"),
  stroke: (left: 3pt + rgb("#6a1b9a")),
  inset: 8pt,
  radius: (right: 3pt),
  [*Post:* #body],
)

// Function signature box
#let func-sig(sig) = block(
  width: 100%,
  fill: rgb("#fafafa"),
  stroke: 1pt + rgb("#bdbdbd"),
  inset: 10pt,
  radius: 3pt,
  raw(sig, lang: "c"),
)

// Parameter table
#let param-table(..rows) = {
  table(
    columns: (auto, auto, 1fr),
    stroke: 0.5pt + rgb("#e0e0e0"),
    inset: 6pt,
    fill: (_, y) => if y == 0 { rgb("#e3f2fd") } else { none },
    [*Direction*], [*Name*], [*Description*],
    ..rows.pos().flatten(),
  )
}

// Return value table
#let retval-table(..rows) = {
  table(
    columns: (auto, 1fr),
    stroke: 0.5pt + rgb("#e0e0e0"),
    inset: 6pt,
    fill: (_, y) => if y == 0 { rgb("#e3f2fd") } else { none },
    [*Value*], [*Description*],
    ..rows.pos().flatten(),
  )
}
