#import "_template.typ": *

// Title page
#align(center)[
  #v(3cm)
  #text(28pt, weight: "bold", fill: rgb("#1565c0"))[STAR - Simultaneous Tracking and Robotics]
  #v(1cm)
  #text(14pt, fill: rgb("#666666"))[Complete System Documentation]
  #v(0.5cm)
  #text(12pt)[Version 1.0.0]
  #v(0.5cm)
  #text(10pt, fill: rgb("#999999"))[Generated by star-docs]
  #v(2cm)
]
#pagebreak()

// Table of Contents
#outline(depth: 3)
#pagebreak()

#include "api_rx72n_firmware.typ"
#include "api_gateway_service.typ"
#include "api_ros2_packages.typ"
#include "api_protocol_buffers.typ"
#include "api_user_interface.typ"
