version: "2"
run:
  build-tags:
    - integration
  tests: true
linters:
  enable:
    - revive
  settings:
    revive:
      rules:
        - name: package-comments
          disabled: true
        - name: exported
          disabled: false
        - name: var-naming
          disabled: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - all
        path: .*\.pb\.go
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - vendor
      - third_party
      - testdata
      - gen
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - .*\.pb\.go
      - .*\.gen\.go
      - vendor
      - third_party
      - testdata
      - gen
      - third_party$
      - builtin$
      - examples$
