#!/usr/bin/env bash
# grafana-render-pdf.sh -- build STAR_Grafana_Render.pdf from per-panel PNGs.
#
# Reads docs/grafana-screenshots/manifest.txt (produced by
# scripts/render-grafana-json.py) and emits a multi-page PDF where each page
# embeds one PNG with its row + panel title.
#
# Page order:
#   1. Cover
#   2. Dashboard overview
#   3. One page per row (composite of all panels in that row)
#   4. One page per individual panel, grouped by row
#
# ASCII-only source. Output goes to docs/pdfs/ops/STAR_Grafana_Render.pdf so
# the existing combined-ops target can concat it with STAR_Grafana.pdf (the
# JSON listing) into docs/STAR_Ops_Combined.pdf.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SCREENSHOT_DIR="${REPO_ROOT}/docs/grafana-screenshots"
MANIFEST="${SCREENSHOT_DIR}/manifest.txt"
OUT_DIR="${REPO_ROOT}/docs/pdfs/ops"
OUT_PDF="${OUT_DIR}/STAR_Grafana_Render.pdf"

if [ ! -f "${MANIFEST}" ]; then
  echo "ERROR: manifest not found: ${MANIFEST}"
  echo "Run: python3 scripts/render-grafana-json.py"
  exit 1
fi

mkdir -p "${OUT_DIR}"

# Build TeX source in a tmpdir to avoid polluting the repo with .aux/.log
TMPDIR_LOCAL="$(mktemp -d)"
trap 'rm -rf "${TMPDIR_LOCAL}"' EXIT
TEX="${TMPDIR_LOCAL}/grafana_render.tex"

# LaTeX-escape helper -- strips LaTeX special chars
latex_escape() {
  printf '%s' "$1" \
    | sed 's/\\/\\textbackslash{}/g
           s/_/\\_/g
           s/&/\\&/g
           s/#/\\#/g
           s/\$/\\$/g
           s/%/\\%/g
           s/\^/\\^{}/g
           s/{/\\{/g
           s/}/\\}/g
           s/~/\\~{}/g'
}

cat > "${TEX}" <<'EOF'
\documentclass[10pt]{article}
\usepackage[a4paper,margin=15mm]{geometry}
\usepackage{graphicx}
\usepackage{xcolor}
\usepackage{hyperref}
\usepackage{fancyhdr}
\hypersetup{
  pdftitle={STAR Grafana Dashboard - Rendered Snapshot},
  pdfauthor={STAR project},
  pdfsubject={Grafana dashboard visual snapshots},
  colorlinks=true,
  linkcolor=blue
}
\definecolor{starbg}{RGB}{24,27,31}
\setlength{\parindent}{0pt}
\setlength{\parskip}{0.5em}
\pagestyle{fancy}
\fancyhf{}
\fancyhead[L]{STAR robot telemetry}
\fancyhead[R]{Rendered snapshot}
\fancyfoot[C]{\thepage}
\renewcommand{\headrulewidth}{0.4pt}

\begin{document}

\thispagestyle{empty}
\vspace*{2cm}
\begin{center}
{\Huge\bfseries STAR Grafana Dashboard}\\[0.5em]
{\Large Rendered Snapshot}\\[2em]
\rule{0.6\textwidth}{0.5pt}\\[1em]
\textit{Visual representations of every panel in the\\
\texttt{monitoring/grafana-star-dashboard.json} dashboard.}\\[1.5em]
Generated by \texttt{scripts/render-grafana-json.py}\\
using offline PIL rendering with synthetic demo data.\\[2em]

To capture screenshots of the production dashboard with live\\
Prometheus data, deploy via \texttt{monitoring/docker-compose.yml}\\
and use the grafana-image-renderer plugin.
\end{center}
\newpage

EOF

emit_image_page() {
  # $1 = filename relative to SCREENSHOT_DIR, $2 = page title, $3 = subtitle
  local fname="$1"
  local title="$2"
  local subtitle="$3"
  local title_esc subtitle_esc fname_esc
  title_esc="$(latex_escape "${title}")"
  subtitle_esc="$(latex_escape "${subtitle}")"
  fname_esc="${fname}"  # filenames are slugified ASCII, no escaping needed

  cat >> "${TEX}" <<EOF
\begin{center}
{\large\bfseries ${title_esc}}\\\\[0.3em]
{\small\itshape ${subtitle_esc}}
\end{center}
\vspace{0.5em}
\begin{center}
\includegraphics[width=\textwidth,keepaspectratio,height=0.78\textheight]{${fname_esc}}
\end{center}
\newpage

EOF
}

# Section header pages
emit_section() {
  local title="$1"
  local title_esc
  title_esc="$(latex_escape "${title}")"
  cat >> "${TEX}" <<EOF
\vspace*{4cm}
\begin{center}
{\Huge\bfseries ${title_esc}}
\end{center}
\newpage

EOF
}

# Walk manifest. Format:  kind|fname|row_idx|row_title|title
emit_section "Dashboard Overview"
while IFS='|' read -r kind fname row_idx row_title title; do
  case "${kind}" in
    "#"*|"") continue ;;
    overview)
      emit_image_page "${fname}" "${title}" "Composite of all rows"
      ;;
  esac
done < "${MANIFEST}"

emit_section "Per-Row Composites"
while IFS='|' read -r kind fname row_idx row_title title; do
  case "${kind}" in
    "#"*|"") continue ;;
    row)
      emit_image_page "${fname}" "${title}" \
        "All panels in this row, arranged on the Grafana 24-column grid"
      ;;
  esac
done < "${MANIFEST}"

emit_section "Individual Panels"
# Group by row -- iterate rows in order, then panels within each row
prev_row=""
while IFS='|' read -r kind fname row_idx row_title title; do
  case "${kind}" in
    "#"*|"") continue ;;
    panel)
      if [ "${row_idx}" != "${prev_row}" ]; then
        # New row -- emit a small section divider page
        emit_section "Row ${row_idx}: ${row_title}"
        prev_row="${row_idx}"
      fi
      emit_image_page "${fname}" "${title}" \
        "Row ${row_idx}: ${row_title}"
      ;;
  esac
done < "${MANIFEST}"

cat >> "${TEX}" <<'EOF'
\end{document}
EOF

# Copy images so xelatex can find them via TEXINPUTS
cp "${SCREENSHOT_DIR}"/*.png "${TMPDIR_LOCAL}/"

# Compile (twice to resolve hyperref refs)
echo "Compiling LaTeX..."
(
  cd "${TMPDIR_LOCAL}"
  xelatex -interaction=nonstopmode -halt-on-error grafana_render.tex \
    > xelatex.log 2>&1 || {
      echo "ERROR: xelatex failed. Tail of log:"
      tail -40 xelatex.log
      exit 1
    }
  xelatex -interaction=nonstopmode -halt-on-error grafana_render.tex \
    > xelatex.log 2>&1 || true
)

cp "${TMPDIR_LOCAL}/grafana_render.pdf" "${OUT_PDF}"
echo "[OK] ${OUT_PDF}"
which pdfinfo >/dev/null 2>&1 && pdfinfo "${OUT_PDF}" | grep -E 'Pages|File size' || true
