/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,optimize_code_size,generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "star/v1/battery_management.proto" (package "star.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// battery_management.proto - STAR Battery Management Protocol Buffer Definitions
// BQ7850 BMS monitoring and control service for battery pack management.
//
// Following Boston Dynamics style guide:
// - Proto3 only, 100 char line limit, 4 space indent
// - MKS units with suffixes (_mv, _ma, _mw, _deci_celsius)
// - All fields documented with units and valid ranges
//
// STAR Project - Texas A&M University
// December 2025
//
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { BatteryManagementService } from "./battery_management";
import type { ResetDeviceResponse } from "./battery_management";
import type { ResetDeviceRequest } from "./battery_management";
import type { GetDeviceInfoResponse } from "./battery_management";
import type { GetDeviceInfoRequest } from "./battery_management";
import type { ControlFetsResponse } from "./battery_management";
import type { ControlFetsRequest } from "./battery_management";
import type { GetBalancingStatusResponse } from "./battery_management";
import type { GetBalancingStatusRequest } from "./battery_management";
import type { DisableCellBalancingResponse } from "./battery_management";
import type { DisableCellBalancingRequest } from "./battery_management";
import type { EnableCellBalancingResponse } from "./battery_management";
import type { EnableCellBalancingRequest } from "./battery_management";
import type { SetProtectionThresholdsResponse } from "./battery_management";
import type { SetProtectionThresholdsRequest } from "./battery_management";
import type { GetProtectionThresholdsResponse } from "./battery_management";
import type { GetProtectionThresholdsRequest } from "./battery_management";
import type { BatteryState } from "./battery_management";
import type { StreamBatteryStateRequest } from "./battery_management";
import type { ServerStreamingCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { GetBatteryStateResponse } from "./battery_management";
import type { GetBatteryStateRequest } from "./battery_management";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * Battery management service for BQ7850 BMS monitoring and control.
 * Provides state queries, streaming telemetry, protection configuration,
 * cell balancing, and FET control for lithium-ion battery packs.
 *
 * @generated from protobuf service star.v1.BatteryManagementService
 */
export interface IBatteryManagementServiceClient {
    /**
     * Get current battery state (cells, temps, current, SOC, status).
     * Returns a complete snapshot of all battery parameters.
     *
     * @generated from protobuf rpc: GetBatteryState
     */
    getBatteryState(input: GetBatteryStateRequest, options?: RpcOptions): UnaryCall<GetBatteryStateRequest, GetBatteryStateResponse>;
    /**
     * Stream battery state at configured rate.
     * Server streams battery state updates continuously.
     *
     * @generated from protobuf rpc: StreamBatteryState
     */
    streamBatteryState(input: StreamBatteryStateRequest, options?: RpcOptions): ServerStreamingCall<StreamBatteryStateRequest, BatteryState>;
    /**
     * Get protection thresholds configuration.
     *
     * @generated from protobuf rpc: GetProtectionThresholds
     */
    getProtectionThresholds(input: GetProtectionThresholdsRequest, options?: RpcOptions): UnaryCall<GetProtectionThresholdsRequest, GetProtectionThresholdsResponse>;
    /**
     * Set protection thresholds (requires device unsealed).
     *
     * @generated from protobuf rpc: SetProtectionThresholds
     */
    setProtectionThresholds(input: SetProtectionThresholdsRequest, options?: RpcOptions): UnaryCall<SetProtectionThresholdsRequest, SetProtectionThresholdsResponse>;
    /**
     * Enable cell balancing for specified cells.
     *
     * @generated from protobuf rpc: EnableCellBalancing
     */
    enableCellBalancing(input: EnableCellBalancingRequest, options?: RpcOptions): UnaryCall<EnableCellBalancingRequest, EnableCellBalancingResponse>;
    /**
     * Disable all cell balancing.
     *
     * @generated from protobuf rpc: DisableCellBalancing
     */
    disableCellBalancing(input: DisableCellBalancingRequest, options?: RpcOptions): UnaryCall<DisableCellBalancingRequest, DisableCellBalancingResponse>;
    /**
     * Get cell balancing status.
     *
     * @generated from protobuf rpc: GetBalancingStatus
     */
    getBalancingStatus(input: GetBalancingStatusRequest, options?: RpcOptions): UnaryCall<GetBalancingStatusRequest, GetBalancingStatusResponse>;
    /**
     * Control charge/discharge FETs.
     *
     * @generated from protobuf rpc: ControlFets
     */
    controlFets(input: ControlFetsRequest, options?: RpcOptions): UnaryCall<ControlFetsRequest, ControlFetsResponse>;
    /**
     * Get BMS device information (manufacturer, serial, chemistry).
     *
     * @generated from protobuf rpc: GetDeviceInfo
     */
    getDeviceInfo(input: GetDeviceInfoRequest, options?: RpcOptions): UnaryCall<GetDeviceInfoRequest, GetDeviceInfoResponse>;
    /**
     * Reset BMS device (soft reset).
     *
     * @generated from protobuf rpc: ResetDevice
     */
    resetDevice(input: ResetDeviceRequest, options?: RpcOptions): UnaryCall<ResetDeviceRequest, ResetDeviceResponse>;
}
/**
 * Battery management service for BQ7850 BMS monitoring and control.
 * Provides state queries, streaming telemetry, protection configuration,
 * cell balancing, and FET control for lithium-ion battery packs.
 *
 * @generated from protobuf service star.v1.BatteryManagementService
 */
export class BatteryManagementServiceClient implements IBatteryManagementServiceClient, ServiceInfo {
    typeName = BatteryManagementService.typeName;
    methods = BatteryManagementService.methods;
    options = BatteryManagementService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * Get current battery state (cells, temps, current, SOC, status).
     * Returns a complete snapshot of all battery parameters.
     *
     * @generated from protobuf rpc: GetBatteryState
     */
    getBatteryState(input: GetBatteryStateRequest, options?: RpcOptions): UnaryCall<GetBatteryStateRequest, GetBatteryStateResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBatteryStateRequest, GetBatteryStateResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Stream battery state at configured rate.
     * Server streams battery state updates continuously.
     *
     * @generated from protobuf rpc: StreamBatteryState
     */
    streamBatteryState(input: StreamBatteryStateRequest, options?: RpcOptions): ServerStreamingCall<StreamBatteryStateRequest, BatteryState> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<StreamBatteryStateRequest, BatteryState>("serverStreaming", this._transport, method, opt, input);
    }
    /**
     * Get protection thresholds configuration.
     *
     * @generated from protobuf rpc: GetProtectionThresholds
     */
    getProtectionThresholds(input: GetProtectionThresholdsRequest, options?: RpcOptions): UnaryCall<GetProtectionThresholdsRequest, GetProtectionThresholdsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProtectionThresholdsRequest, GetProtectionThresholdsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Set protection thresholds (requires device unsealed).
     *
     * @generated from protobuf rpc: SetProtectionThresholds
     */
    setProtectionThresholds(input: SetProtectionThresholdsRequest, options?: RpcOptions): UnaryCall<SetProtectionThresholdsRequest, SetProtectionThresholdsResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<SetProtectionThresholdsRequest, SetProtectionThresholdsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Enable cell balancing for specified cells.
     *
     * @generated from protobuf rpc: EnableCellBalancing
     */
    enableCellBalancing(input: EnableCellBalancingRequest, options?: RpcOptions): UnaryCall<EnableCellBalancingRequest, EnableCellBalancingResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<EnableCellBalancingRequest, EnableCellBalancingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Disable all cell balancing.
     *
     * @generated from protobuf rpc: DisableCellBalancing
     */
    disableCellBalancing(input: DisableCellBalancingRequest, options?: RpcOptions): UnaryCall<DisableCellBalancingRequest, DisableCellBalancingResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<DisableCellBalancingRequest, DisableCellBalancingResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get cell balancing status.
     *
     * @generated from protobuf rpc: GetBalancingStatus
     */
    getBalancingStatus(input: GetBalancingStatusRequest, options?: RpcOptions): UnaryCall<GetBalancingStatusRequest, GetBalancingStatusResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetBalancingStatusRequest, GetBalancingStatusResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Control charge/discharge FETs.
     *
     * @generated from protobuf rpc: ControlFets
     */
    controlFets(input: ControlFetsRequest, options?: RpcOptions): UnaryCall<ControlFetsRequest, ControlFetsResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<ControlFetsRequest, ControlFetsResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Get BMS device information (manufacturer, serial, chemistry).
     *
     * @generated from protobuf rpc: GetDeviceInfo
     */
    getDeviceInfo(input: GetDeviceInfoRequest, options?: RpcOptions): UnaryCall<GetDeviceInfoRequest, GetDeviceInfoResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetDeviceInfoRequest, GetDeviceInfoResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * Reset BMS device (soft reset).
     *
     * @generated from protobuf rpc: ResetDevice
     */
    resetDevice(input: ResetDeviceRequest, options?: RpcOptions): UnaryCall<ResetDeviceRequest, ResetDeviceResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ResetDeviceRequest, ResetDeviceResponse>("unary", this._transport, method, opt, input);
    }
}
