/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,optimize_code_size,generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "star/v1/gateway_service.proto" (package "star.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// gateway_service.proto - STAR Gateway Service Protocol Buffer Definitions
// gRPC service for bidirectional communication between ROS2 and Gateway (UI).
//
// Architecture:
//   ROS2 (C++) <-> gRPC <-> Gateway (Go) <-> WebSocket <-> UI (TypeScript)
//
// Following Boston Dynamics style guide:
// - Proto3 only, 100 char line limit, 4 space indent
// - MKS units (meters per second, radians)
// - All fields documented with units and valid ranges
//
// Copyright (c) 2026 Locked Inc.
// SPDX-License-Identifier: MIT
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { PidConfig } from "./motor_control";
import { VelocityCommand } from "./motor_control";
import { ResponseHeader } from "./common";
import { LidarScan } from "./ui";
import { OdometryData } from "./ui";
import { MotorStatus } from "./motor_control";
import { TelemetryData } from "./telemetry";
import { SystemStatus } from "./telemetry";
import { RequestHeader } from "./common";
// ============================================================================
// ForwardTelemetry: ROS2 -> Gateway -> UI
// ============================================================================

/**
 * Request to forward telemetry from ROS2 to Gateway.
 *
 * @generated from protobuf message star.v1.ForwardTelemetryRequest
 */
export interface ForwardTelemetryRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
    /**
     * Robot system status (mode, connections, uptime).
     * Forwarded from /robot_status ROS2 topic.
     *
     * @generated from protobuf field: star.v1.SystemStatus system_status = 2
     */
    systemStatus?: SystemStatus;
    /**
     * Optional: Additional telemetry data (IMU, GPS, etc.).
     *
     * @generated from protobuf field: star.v1.TelemetryData telemetry = 4
     */
    telemetry?: TelemetryData;
    /**
     * Per-motor status for all drive motors.
     * Forwarded from /motor_status ROS2 topic.
     * nanopb: max_count:4 (4-motor drive configuration; defined in gateway_service.options).
     *
     * @generated from protobuf field: repeated star.v1.MotorStatus motor_status = 5
     */
    motorStatus: MotorStatus[];
    /**
     * Robot pose and velocity from wheel odometry.
     * Forwarded from /odometry ROS2 topic.
     * nanopb: OdometryData contains only fixed-width scalar fields (double, int64);
     *   no repeated fields or variable-length strings, so no max_size/max_count
     *   constraints are needed beyond those enforced by the message field types.
     *
     * @generated from protobuf field: star.v1.OdometryData odometry = 6
     */
    odometry?: OdometryData;
    /**
     * Latest LiDAR scan from RPLiDAR C1.
     * Forwarded from /scan ROS2 topic.
     * nanopb: LidarScan.angle_rad, LidarScan.range_m, and LidarScan.intensity are
     *   bounded by max_count:500 (RPLiDAR C1 ~500 samples per revolution at
     *   10 Hz scan mode -- 5 kHz sample rate / 10 Hz = 500 samples).
     *   Defined in ui.options and duplicated in gateway_service.options.
     *
     * @generated from protobuf field: star.v1.LidarScan lidar_scan = 7
     */
    lidarScan?: LidarScan;
}
/**
 * Response to telemetry forwarding.
 *
 * @generated from protobuf message star.v1.ForwardTelemetryResponse
 */
export interface ForwardTelemetryResponse {
    /**
     * Standard response header.
     *
     * @generated from protobuf field: star.v1.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * True if telemetry was successfully cached for UI streaming.
     *
     * @generated from protobuf field: bool cached = 2
     */
    cached: boolean;
    /**
     * Number of active UI WebSocket clients receiving this telemetry.
     *
     * @generated from protobuf field: int32 active_clients = 3
     */
    activeClients: number;
}
// ============================================================================
// GetTeleopCommand: UI -> Gateway -> ROS2
// ============================================================================

/**
 * Request for latest teleop command from Gateway.
 *
 * @generated from protobuf message star.v1.GetTeleopCommandRequest
 */
export interface GetTeleopCommandRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
}
/**
 * Response with latest teleop command.
 *
 * @generated from protobuf message star.v1.GetTeleopCommandResponse
 */
export interface GetTeleopCommandResponse {
    /**
     * Standard response header.
     *
     * @generated from protobuf field: star.v1.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * Latest velocity command from UI.
     * If no command received yet, contains zero velocities.
     *
     * @generated from protobuf field: star.v1.VelocityCommand command = 2
     */
    command?: VelocityCommand;
    /**
     * True if a valid command is available (not just zeros).
     *
     * @generated from protobuf field: bool command_available = 3
     */
    commandAvailable: boolean;
    /**
     * Age of command in milliseconds (for staleness checking).
     * ROS2 should reject commands older than 500ms.
     *
     * @generated from protobuf field: int64 command_age_ms = 4
     */
    commandAgeMs: string;
}
// ============================================================================
// SetPidGains: UI -> Gateway -> ROS2 -> Motor Controller
// ============================================================================

/**
 * Request to set PID gains for motor velocity control.
 *
 * @generated from protobuf message star.v1.SetPidGainsRequest
 */
export interface SetPidGainsRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
    /**
     * PID configuration to apply.
     *
     * @generated from protobuf field: star.v1.PidConfig pid_config = 2
     */
    pidConfig?: PidConfig;
    /**
     * Motor ID to configure (0 = left, 1 = right, -1 = both).
     *
     * @generated from protobuf field: int32 motor_id = 3
     */
    motorId: number;
}
/**
 * Response to PID gains update.
 *
 * @generated from protobuf message star.v1.SetPidGainsResponse
 */
export interface SetPidGainsResponse {
    /**
     * Standard response header.
     *
     * @generated from protobuf field: star.v1.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * True if gains were successfully applied to motor controller.
     *
     * @generated from protobuf field: bool success = 2
     */
    success: boolean;
    /**
     * Human-readable message (e.g., "PID gains updated for both motors").
     *
     * @generated from protobuf field: string message = 3
     */
    message: string;
}
// @generated message type with reflection information, may provide speed optimized methods
class ForwardTelemetryRequest$Type extends MessageType<ForwardTelemetryRequest> {
    constructor() {
        super("star.v1.ForwardTelemetryRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader },
            { no: 2, name: "system_status", kind: "message", T: () => SystemStatus },
            { no: 4, name: "telemetry", kind: "message", T: () => TelemetryData },
            { no: 5, name: "motor_status", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => MotorStatus },
            { no: 6, name: "odometry", kind: "message", T: () => OdometryData },
            { no: 7, name: "lidar_scan", kind: "message", T: () => LidarScan }
        ]);
    }
    create(value?: PartialMessage<ForwardTelemetryRequest>): ForwardTelemetryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.motorStatus = [];
        if (value !== undefined)
            reflectionMergePartial<ForwardTelemetryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ForwardTelemetryRequest): ForwardTelemetryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* star.v1.SystemStatus system_status */ 2:
                    message.systemStatus = SystemStatus.internalBinaryRead(reader, reader.uint32(), options, message.systemStatus);
                    break;
                case /* star.v1.TelemetryData telemetry */ 4:
                    message.telemetry = TelemetryData.internalBinaryRead(reader, reader.uint32(), options, message.telemetry);
                    break;
                case /* repeated star.v1.MotorStatus motor_status */ 5:
                    message.motorStatus.push(MotorStatus.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                case /* star.v1.OdometryData odometry */ 6:
                    message.odometry = OdometryData.internalBinaryRead(reader, reader.uint32(), options, message.odometry);
                    break;
                case /* star.v1.LidarScan lidar_scan */ 7:
                    message.lidarScan = LidarScan.internalBinaryRead(reader, reader.uint32(), options, message.lidarScan);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ForwardTelemetryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.SystemStatus system_status = 2; */
        if (message.systemStatus)
            SystemStatus.internalBinaryWrite(message.systemStatus, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.TelemetryData telemetry = 4; */
        if (message.telemetry)
            TelemetryData.internalBinaryWrite(message.telemetry, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* repeated star.v1.MotorStatus motor_status = 5; */
        for (let i = 0; i < message.motorStatus.length; i++)
            MotorStatus.internalBinaryWrite(message.motorStatus[i], writer.tag(5, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.OdometryData odometry = 6; */
        if (message.odometry)
            OdometryData.internalBinaryWrite(message.odometry, writer.tag(6, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.LidarScan lidar_scan = 7; */
        if (message.lidarScan)
            LidarScan.internalBinaryWrite(message.lidarScan, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.ForwardTelemetryRequest
 */
export const ForwardTelemetryRequest = new ForwardTelemetryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ForwardTelemetryResponse$Type extends MessageType<ForwardTelemetryResponse> {
    constructor() {
        super("star.v1.ForwardTelemetryResponse", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "cached", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "active_clients", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<ForwardTelemetryResponse>): ForwardTelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.cached = false;
        message.activeClients = 0;
        if (value !== undefined)
            reflectionMergePartial<ForwardTelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ForwardTelemetryResponse): ForwardTelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* bool cached */ 2:
                    message.cached = reader.bool();
                    break;
                case /* int32 active_clients */ 3:
                    message.activeClients = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ForwardTelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool cached = 2; */
        if (message.cached !== false)
            writer.tag(2, WireType.Varint).bool(message.cached);
        /* int32 active_clients = 3; */
        if (message.activeClients !== 0)
            writer.tag(3, WireType.Varint).int32(message.activeClients);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.ForwardTelemetryResponse
 */
export const ForwardTelemetryResponse = new ForwardTelemetryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTeleopCommandRequest$Type extends MessageType<GetTeleopCommandRequest> {
    constructor() {
        super("star.v1.GetTeleopCommandRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader }
        ]);
    }
    create(value?: PartialMessage<GetTeleopCommandRequest>): GetTeleopCommandRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTeleopCommandRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTeleopCommandRequest): GetTeleopCommandRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTeleopCommandRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetTeleopCommandRequest
 */
export const GetTeleopCommandRequest = new GetTeleopCommandRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTeleopCommandResponse$Type extends MessageType<GetTeleopCommandResponse> {
    constructor() {
        super("star.v1.GetTeleopCommandResponse", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "command", kind: "message", T: () => VelocityCommand },
            { no: 3, name: "command_available", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "command_age_ms", kind: "scalar", T: 3 /*ScalarType.INT64*/ }
        ]);
    }
    create(value?: PartialMessage<GetTeleopCommandResponse>): GetTeleopCommandResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.commandAvailable = false;
        message.commandAgeMs = "0";
        if (value !== undefined)
            reflectionMergePartial<GetTeleopCommandResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTeleopCommandResponse): GetTeleopCommandResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* star.v1.VelocityCommand command */ 2:
                    message.command = VelocityCommand.internalBinaryRead(reader, reader.uint32(), options, message.command);
                    break;
                case /* bool command_available */ 3:
                    message.commandAvailable = reader.bool();
                    break;
                case /* int64 command_age_ms */ 4:
                    message.commandAgeMs = reader.int64().toString();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTeleopCommandResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.VelocityCommand command = 2; */
        if (message.command)
            VelocityCommand.internalBinaryWrite(message.command, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* bool command_available = 3; */
        if (message.commandAvailable !== false)
            writer.tag(3, WireType.Varint).bool(message.commandAvailable);
        /* int64 command_age_ms = 4; */
        if (message.commandAgeMs !== "0")
            writer.tag(4, WireType.Varint).int64(message.commandAgeMs);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetTeleopCommandResponse
 */
export const GetTeleopCommandResponse = new GetTeleopCommandResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPidGainsRequest$Type extends MessageType<SetPidGainsRequest> {
    constructor() {
        super("star.v1.SetPidGainsRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader },
            { no: 2, name: "pid_config", kind: "message", T: () => PidConfig },
            { no: 3, name: "motor_id", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<SetPidGainsRequest>): SetPidGainsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.motorId = 0;
        if (value !== undefined)
            reflectionMergePartial<SetPidGainsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetPidGainsRequest): SetPidGainsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* star.v1.PidConfig pid_config */ 2:
                    message.pidConfig = PidConfig.internalBinaryRead(reader, reader.uint32(), options, message.pidConfig);
                    break;
                case /* int32 motor_id */ 3:
                    message.motorId = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetPidGainsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.PidConfig pid_config = 2; */
        if (message.pidConfig)
            PidConfig.internalBinaryWrite(message.pidConfig, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* int32 motor_id = 3; */
        if (message.motorId !== 0)
            writer.tag(3, WireType.Varint).int32(message.motorId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.SetPidGainsRequest
 */
export const SetPidGainsRequest = new SetPidGainsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SetPidGainsResponse$Type extends MessageType<SetPidGainsResponse> {
    constructor() {
        super("star.v1.SetPidGainsResponse", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "success", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<SetPidGainsResponse>): SetPidGainsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.success = false;
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<SetPidGainsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SetPidGainsResponse): SetPidGainsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* bool success */ 2:
                    message.success = reader.bool();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SetPidGainsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* bool success = 2; */
        if (message.success !== false)
            writer.tag(2, WireType.Varint).bool(message.success);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.SetPidGainsResponse
 */
export const SetPidGainsResponse = new SetPidGainsResponse$Type();
/**
 * @generated ServiceType for protobuf service star.v1.GatewayService
 */
export const GatewayService = new ServiceType("star.v1.GatewayService", [
    { name: "ForwardTelemetry", options: {}, I: ForwardTelemetryRequest, O: ForwardTelemetryResponse },
    { name: "GetTeleopCommand", options: {}, I: GetTeleopCommandRequest, O: GetTeleopCommandResponse },
    { name: "SetPidGains", options: {}, I: SetPidGainsRequest, O: SetPidGainsResponse }
]);
