/* eslint-disable */
// @generated by protobuf-ts 2.11.1 with parameter long_type_string,optimize_code_size,generate_dependencies,ts_nocheck,eslint_disable
// @generated from protobuf file "star/v1/telemetry.proto" (package "star.v1", syntax proto3)
// tslint:disable
// @ts-nocheck
//
// telemetry.proto - STAR Telemetry Protocol Buffer Definitions
// Real-time sensor data streaming service.
//
// Following Boston Dynamics style guide:
// - Proto3 only, 100 char line limit, 4 space indent
// - MKS units (meters, radians, Celsius)
// - All fields documented with units
//
// STAR Project - Texas A&M University
// December 2025
//
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
import { ResponseHeader } from "./common";
import { RequestHeader } from "./common";
/**
 * Request for telemetry snapshot.
 *
 * @generated from protobuf message star.v1.GetTelemetryRequest
 */
export interface GetTelemetryRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
}
/**
 * Response with telemetry snapshot.
 *
 * @generated from protobuf message star.v1.GetTelemetryResponse
 */
export interface GetTelemetryResponse {
    /**
     * Standard response header.
     *
     * @generated from protobuf field: star.v1.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * Current telemetry data.
     *
     * @generated from protobuf field: star.v1.TelemetryData telemetry = 2
     */
    telemetry?: TelemetryData;
}
/**
 * Request to stream telemetry.
 *
 * @generated from protobuf message star.v1.StreamTelemetryRequest
 */
export interface StreamTelemetryRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
    /**
     * Desired update rate in Hz.
     * Valid range: 1 to 100 Hz.
     *
     * @generated from protobuf field: int32 rate_hz = 2
     */
    rateHz: number;
    /**
     * Fields to include (empty = all fields).
     *
     * @generated from protobuf field: repeated string fields = 3
     */
    fields: string[];
}
/**
 * Request for system status.
 *
 * @generated from protobuf message star.v1.GetSystemStatusRequest
 */
export interface GetSystemStatusRequest {
    /**
     * Standard request header.
     *
     * @generated from protobuf field: star.v1.RequestHeader header = 1
     */
    header?: RequestHeader;
}
/**
 * Response with system status.
 *
 * @generated from protobuf message star.v1.GetSystemStatusResponse
 */
export interface GetSystemStatusResponse {
    /**
     * Standard response header.
     *
     * @generated from protobuf field: star.v1.ResponseHeader header = 1
     */
    header?: ResponseHeader;
    /**
     * System status information.
     *
     * @generated from protobuf field: star.v1.SystemStatus status = 2
     */
    status?: SystemStatus;
}
/**
 * Complete telemetry snapshot from all sensors.
 *
 * @generated from protobuf message star.v1.TelemetryData
 */
export interface TelemetryData {
    /**
     * IMU sensor data.
     *
     * @generated from protobuf field: star.v1.ImuData imu = 1
     */
    imu?: ImuData;
    /**
     * GPS data (if available).
     *
     * @generated from protobuf field: star.v1.GpsData gps = 2
     */
    gps?: GpsData;
    /**
     * Battery state of charge.
     * Range: 0 to 100 percent.
     *
     * @generated from protobuf field: double battery_percent = 3
     */
    batteryPercent: number;
    /**
     * WiFi signal strength in dBm.
     * Typical range: -100 to -30 dBm.
     *
     * @generated from protobuf field: int32 wifi_signal_dbm = 4
     */
    wifiSignalDbm: number;
    /**
     * CPU usage percentage.
     * Range: 0 to 100 percent.
     *
     * @generated from protobuf field: double cpu_usage_percent = 5
     */
    cpuUsagePercent: number;
    /**
     * Temperature in Celsius (from DS18B20 sensor).
     *
     * @generated from protobuf field: double temperature_celsius = 6
     */
    temperatureCelsius: number;
    /**
     * Motor load percentage (average across motors).
     * Range: 0 to 100 percent.
     *
     * @generated from protobuf field: double motor_load_percent = 7
     */
    motorLoadPercent: number;
    /**
     * Telemetry timestamp.
     *
     * @generated from protobuf field: google.protobuf.Timestamp timestamp = 8
     */
    timestamp?: Timestamp;
}
/**
 * IMU sensor data (orientation, velocity, acceleration).
 * Uses MKS units: radians for angles, m/s^2 for acceleration.
 *
 * @generated from protobuf message star.v1.ImuData
 */
export interface ImuData {
    /**
     * Pitch angle in radians.
     * Range: -pi/2 to pi/2.
     *
     * @generated from protobuf field: double pitch_rad = 1
     */
    pitchRad: number;
    /**
     * Roll angle in radians.
     * Range: -pi to pi.
     *
     * @generated from protobuf field: double roll_rad = 2
     */
    rollRad: number;
    /**
     * Yaw angle in radians.
     * Range: -pi to pi.
     *
     * @generated from protobuf field: double yaw_rad = 3
     */
    yawRad: number;
    /**
     * Linear acceleration X in meters per second squared.
     *
     * @generated from protobuf field: double accel_x_mps2 = 4
     */
    accelXMps2: number;
    /**
     * Linear acceleration Y in meters per second squared.
     *
     * @generated from protobuf field: double accel_y_mps2 = 5
     */
    accelYMps2: number;
    /**
     * Linear acceleration Z in meters per second squared.
     * At rest, should read approximately 9.81 m/s^2.
     *
     * @generated from protobuf field: double accel_z_mps2 = 6
     */
    accelZMps2: number;
    /**
     * Angular velocity X (roll rate) in radians per second.
     *
     * @generated from protobuf field: double gyro_x_rad_per_s = 7
     */
    gyroXRadPerS: number;
    /**
     * Angular velocity Y (pitch rate) in radians per second.
     *
     * @generated from protobuf field: double gyro_y_rad_per_s = 8
     */
    gyroYRadPerS: number;
    /**
     * Angular velocity Z (yaw rate) in radians per second.
     *
     * @generated from protobuf field: double gyro_z_rad_per_s = 9
     */
    gyroZRadPerS: number;
}
/**
 * GPS position data.
 *
 * @generated from protobuf message star.v1.GpsData
 */
export interface GpsData {
    /**
     * WGS84 latitude in degrees.
     * Range: -90 to 90.
     *
     * @generated from protobuf field: double latitude_deg = 1
     */
    latitudeDeg: number;
    /**
     * WGS84 longitude in degrees.
     * Range: -180 to 180.
     *
     * @generated from protobuf field: double longitude_deg = 2
     */
    longitudeDeg: number;
    /**
     * Altitude above sea level in meters.
     *
     * @generated from protobuf field: double altitude_m = 3
     */
    altitudeM: number;
    /**
     * Horizontal accuracy estimate in meters.
     *
     * @generated from protobuf field: double accuracy_m = 4
     */
    accuracyM: number;
    /**
     * Number of satellites in view.
     *
     * @generated from protobuf field: int32 satellites = 5
     */
    satellites: number;
    /**
     * GPS fix type.
     *
     * @generated from protobuf field: star.v1.GpsFix fix_type = 6
     */
    fixType: GpsFix;
}
/**
 * Complete system status information.
 *
 * @generated from protobuf message star.v1.SystemStatus
 */
export interface SystemStatus {
    /**
     * Overall connection state.
     *
     * @generated from protobuf field: star.v1.ConnectionStatus connection_status = 1
     */
    connectionStatus: ConnectionStatus;
    /**
     * Current operating mode.
     *
     * @generated from protobuf field: star.v1.RobotMode mode = 2
     */
    mode: RobotMode;
    /**
     * ESP32 motor controller connected.
     *
     * @generated from protobuf field: bool esp32_connected = 3
     */
    esp32Connected: boolean;
    /**
     * LiDAR sensor connected.
     *
     * @generated from protobuf field: bool lidar_connected = 4
     */
    lidarConnected: boolean;
    /**
     * ROS2 bridge connected.
     *
     * @generated from protobuf field: bool ros_connected = 5
     */
    rosConnected: boolean;
    /**
     * ESP32 firmware version string.
     *
     * @generated from protobuf field: string firmware_version = 6
     */
    firmwareVersion: string;
    /**
     * System uptime in seconds.
     *
     * @generated from protobuf field: uint64 uptime_s = 7
     */
    uptimeS: string;
    /**
     * Free heap memory in bytes.
     *
     * @generated from protobuf field: uint32 free_heap_bytes = 8
     */
    freeHeapBytes: number;
}
/**
 * GPS fix type.
 *
 * @generated from protobuf enum star.v1.GpsFix
 */
export enum GpsFix {
    /**
     * Unknown fix type.
     *
     * @generated from protobuf enum value: GPS_FIX_UNKNOWN = 0;
     */
    GPS_FIX_UNKNOWN = 0,
    /**
     * No fix available.
     *
     * @generated from protobuf enum value: GPS_FIX_NONE = 1;
     */
    GPS_FIX_NONE = 1,
    /**
     * 2D fix (latitude/longitude only).
     *
     * @generated from protobuf enum value: GPS_FIX_2D = 2;
     */
    GPS_FIX_2D = 2,
    /**
     * 3D fix (latitude/longitude/altitude).
     *
     * @generated from protobuf enum value: GPS_FIX_3D = 3;
     */
    GPS_FIX_3D = 3,
    /**
     * Differential GPS fix.
     *
     * @generated from protobuf enum value: GPS_FIX_DGPS = 4;
     */
    GPS_FIX_DGPS = 4,
    /**
     * RTK float solution.
     *
     * @generated from protobuf enum value: GPS_FIX_RTK_FLOAT = 5;
     */
    GPS_FIX_RTK_FLOAT = 5,
    /**
     * RTK fixed solution.
     *
     * @generated from protobuf enum value: GPS_FIX_RTK_FIXED = 6;
     */
    GPS_FIX_RTK_FIXED = 6
}
/**
 * Connection state enumeration.
 *
 * @generated from protobuf enum star.v1.ConnectionStatus
 */
export enum ConnectionStatus {
    /**
     * Unknown connection state.
     *
     * @generated from protobuf enum value: CONNECTION_STATUS_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * Connected and communicating.
     *
     * @generated from protobuf enum value: CONNECTION_STATUS_CONNECTED = 1;
     */
    CONNECTED = 1,
    /**
     * Not connected.
     *
     * @generated from protobuf enum value: CONNECTION_STATUS_DISCONNECTED = 2;
     */
    DISCONNECTED = 2,
    /**
     * Connection in progress.
     *
     * @generated from protobuf enum value: CONNECTION_STATUS_CONNECTING = 3;
     */
    CONNECTING = 3,
    /**
     * Connection error occurred.
     *
     * @generated from protobuf enum value: CONNECTION_STATUS_ERROR = 4;
     */
    ERROR = 4
}
/**
 * Robot operating mode enumeration.
 *
 * @generated from protobuf enum star.v1.RobotMode
 */
export enum RobotMode {
    /**
     * Unknown operating mode.
     *
     * @generated from protobuf enum value: ROBOT_MODE_UNKNOWN = 0;
     */
    UNKNOWN = 0,
    /**
     * Robot is idle (motors off).
     *
     * @generated from protobuf enum value: ROBOT_MODE_IDLE = 1;
     */
    IDLE = 1,
    /**
     * Manual control mode (joystick/UI).
     *
     * @generated from protobuf enum value: ROBOT_MODE_MANUAL = 2;
     */
    MANUAL = 2,
    /**
     * Autonomous navigation mode (Nav2).
     *
     * @generated from protobuf enum value: ROBOT_MODE_AUTONOMOUS = 3;
     */
    AUTONOMOUS = 3,
    /**
     * SLAM mapping mode.
     *
     * @generated from protobuf enum value: ROBOT_MODE_MAPPING = 4;
     */
    MAPPING = 4,
    /**
     * Emergency stop active.
     *
     * @generated from protobuf enum value: ROBOT_MODE_EMERGENCY_STOP = 5;
     */
    EMERGENCY_STOP = 5
}
// @generated message type with reflection information, may provide speed optimized methods
class GetTelemetryRequest$Type extends MessageType<GetTelemetryRequest> {
    constructor() {
        super("star.v1.GetTelemetryRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader }
        ]);
    }
    create(value?: PartialMessage<GetTelemetryRequest>): GetTelemetryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTelemetryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTelemetryRequest): GetTelemetryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTelemetryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetTelemetryRequest
 */
export const GetTelemetryRequest = new GetTelemetryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetTelemetryResponse$Type extends MessageType<GetTelemetryResponse> {
    constructor() {
        super("star.v1.GetTelemetryResponse", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "telemetry", kind: "message", T: () => TelemetryData }
        ]);
    }
    create(value?: PartialMessage<GetTelemetryResponse>): GetTelemetryResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetTelemetryResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetTelemetryResponse): GetTelemetryResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* star.v1.TelemetryData telemetry */ 2:
                    message.telemetry = TelemetryData.internalBinaryRead(reader, reader.uint32(), options, message.telemetry);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetTelemetryResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.TelemetryData telemetry = 2; */
        if (message.telemetry)
            TelemetryData.internalBinaryWrite(message.telemetry, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetTelemetryResponse
 */
export const GetTelemetryResponse = new GetTelemetryResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class StreamTelemetryRequest$Type extends MessageType<StreamTelemetryRequest> {
    constructor() {
        super("star.v1.StreamTelemetryRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader },
            { no: 2, name: "rate_hz", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "fields", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<StreamTelemetryRequest>): StreamTelemetryRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rateHz = 0;
        message.fields = [];
        if (value !== undefined)
            reflectionMergePartial<StreamTelemetryRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: StreamTelemetryRequest): StreamTelemetryRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* int32 rate_hz */ 2:
                    message.rateHz = reader.int32();
                    break;
                case /* repeated string fields */ 3:
                    message.fields.push(reader.string());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: StreamTelemetryRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* int32 rate_hz = 2; */
        if (message.rateHz !== 0)
            writer.tag(2, WireType.Varint).int32(message.rateHz);
        /* repeated string fields = 3; */
        for (let i = 0; i < message.fields.length; i++)
            writer.tag(3, WireType.LengthDelimited).string(message.fields[i]);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.StreamTelemetryRequest
 */
export const StreamTelemetryRequest = new StreamTelemetryRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSystemStatusRequest$Type extends MessageType<GetSystemStatusRequest> {
    constructor() {
        super("star.v1.GetSystemStatusRequest", [
            { no: 1, name: "header", kind: "message", T: () => RequestHeader }
        ]);
    }
    create(value?: PartialMessage<GetSystemStatusRequest>): GetSystemStatusRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSystemStatusRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSystemStatusRequest): GetSystemStatusRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.RequestHeader header */ 1:
                    message.header = RequestHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSystemStatusRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.RequestHeader header = 1; */
        if (message.header)
            RequestHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetSystemStatusRequest
 */
export const GetSystemStatusRequest = new GetSystemStatusRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetSystemStatusResponse$Type extends MessageType<GetSystemStatusResponse> {
    constructor() {
        super("star.v1.GetSystemStatusResponse", [
            { no: 1, name: "header", kind: "message", T: () => ResponseHeader },
            { no: 2, name: "status", kind: "message", T: () => SystemStatus }
        ]);
    }
    create(value?: PartialMessage<GetSystemStatusResponse>): GetSystemStatusResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<GetSystemStatusResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetSystemStatusResponse): GetSystemStatusResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ResponseHeader header */ 1:
                    message.header = ResponseHeader.internalBinaryRead(reader, reader.uint32(), options, message.header);
                    break;
                case /* star.v1.SystemStatus status */ 2:
                    message.status = SystemStatus.internalBinaryRead(reader, reader.uint32(), options, message.status);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetSystemStatusResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ResponseHeader header = 1; */
        if (message.header)
            ResponseHeader.internalBinaryWrite(message.header, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.SystemStatus status = 2; */
        if (message.status)
            SystemStatus.internalBinaryWrite(message.status, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GetSystemStatusResponse
 */
export const GetSystemStatusResponse = new GetSystemStatusResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TelemetryData$Type extends MessageType<TelemetryData> {
    constructor() {
        super("star.v1.TelemetryData", [
            { no: 1, name: "imu", kind: "message", T: () => ImuData },
            { no: 2, name: "gps", kind: "message", T: () => GpsData },
            { no: 3, name: "battery_percent", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "wifi_signal_dbm", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 5, name: "cpu_usage_percent", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "temperature_celsius", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "motor_load_percent", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "timestamp", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<TelemetryData>): TelemetryData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.batteryPercent = 0;
        message.wifiSignalDbm = 0;
        message.cpuUsagePercent = 0;
        message.temperatureCelsius = 0;
        message.motorLoadPercent = 0;
        if (value !== undefined)
            reflectionMergePartial<TelemetryData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: TelemetryData): TelemetryData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ImuData imu */ 1:
                    message.imu = ImuData.internalBinaryRead(reader, reader.uint32(), options, message.imu);
                    break;
                case /* star.v1.GpsData gps */ 2:
                    message.gps = GpsData.internalBinaryRead(reader, reader.uint32(), options, message.gps);
                    break;
                case /* double battery_percent */ 3:
                    message.batteryPercent = reader.double();
                    break;
                case /* int32 wifi_signal_dbm */ 4:
                    message.wifiSignalDbm = reader.int32();
                    break;
                case /* double cpu_usage_percent */ 5:
                    message.cpuUsagePercent = reader.double();
                    break;
                case /* double temperature_celsius */ 6:
                    message.temperatureCelsius = reader.double();
                    break;
                case /* double motor_load_percent */ 7:
                    message.motorLoadPercent = reader.double();
                    break;
                case /* google.protobuf.Timestamp timestamp */ 8:
                    message.timestamp = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.timestamp);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: TelemetryData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ImuData imu = 1; */
        if (message.imu)
            ImuData.internalBinaryWrite(message.imu, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* star.v1.GpsData gps = 2; */
        if (message.gps)
            GpsData.internalBinaryWrite(message.gps, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* double battery_percent = 3; */
        if (message.batteryPercent !== 0)
            writer.tag(3, WireType.Bit64).double(message.batteryPercent);
        /* int32 wifi_signal_dbm = 4; */
        if (message.wifiSignalDbm !== 0)
            writer.tag(4, WireType.Varint).int32(message.wifiSignalDbm);
        /* double cpu_usage_percent = 5; */
        if (message.cpuUsagePercent !== 0)
            writer.tag(5, WireType.Bit64).double(message.cpuUsagePercent);
        /* double temperature_celsius = 6; */
        if (message.temperatureCelsius !== 0)
            writer.tag(6, WireType.Bit64).double(message.temperatureCelsius);
        /* double motor_load_percent = 7; */
        if (message.motorLoadPercent !== 0)
            writer.tag(7, WireType.Bit64).double(message.motorLoadPercent);
        /* google.protobuf.Timestamp timestamp = 8; */
        if (message.timestamp)
            Timestamp.internalBinaryWrite(message.timestamp, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.TelemetryData
 */
export const TelemetryData = new TelemetryData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ImuData$Type extends MessageType<ImuData> {
    constructor() {
        super("star.v1.ImuData", [
            { no: 1, name: "pitch_rad", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "roll_rad", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "yaw_rad", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "accel_x_mps2", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "accel_y_mps2", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 6, name: "accel_z_mps2", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 7, name: "gyro_x_rad_per_s", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 8, name: "gyro_y_rad_per_s", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 9, name: "gyro_z_rad_per_s", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ }
        ]);
    }
    create(value?: PartialMessage<ImuData>): ImuData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.pitchRad = 0;
        message.rollRad = 0;
        message.yawRad = 0;
        message.accelXMps2 = 0;
        message.accelYMps2 = 0;
        message.accelZMps2 = 0;
        message.gyroXRadPerS = 0;
        message.gyroYRadPerS = 0;
        message.gyroZRadPerS = 0;
        if (value !== undefined)
            reflectionMergePartial<ImuData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ImuData): ImuData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double pitch_rad */ 1:
                    message.pitchRad = reader.double();
                    break;
                case /* double roll_rad */ 2:
                    message.rollRad = reader.double();
                    break;
                case /* double yaw_rad */ 3:
                    message.yawRad = reader.double();
                    break;
                case /* double accel_x_mps2 */ 4:
                    message.accelXMps2 = reader.double();
                    break;
                case /* double accel_y_mps2 */ 5:
                    message.accelYMps2 = reader.double();
                    break;
                case /* double accel_z_mps2 */ 6:
                    message.accelZMps2 = reader.double();
                    break;
                case /* double gyro_x_rad_per_s */ 7:
                    message.gyroXRadPerS = reader.double();
                    break;
                case /* double gyro_y_rad_per_s */ 8:
                    message.gyroYRadPerS = reader.double();
                    break;
                case /* double gyro_z_rad_per_s */ 9:
                    message.gyroZRadPerS = reader.double();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ImuData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double pitch_rad = 1; */
        if (message.pitchRad !== 0)
            writer.tag(1, WireType.Bit64).double(message.pitchRad);
        /* double roll_rad = 2; */
        if (message.rollRad !== 0)
            writer.tag(2, WireType.Bit64).double(message.rollRad);
        /* double yaw_rad = 3; */
        if (message.yawRad !== 0)
            writer.tag(3, WireType.Bit64).double(message.yawRad);
        /* double accel_x_mps2 = 4; */
        if (message.accelXMps2 !== 0)
            writer.tag(4, WireType.Bit64).double(message.accelXMps2);
        /* double accel_y_mps2 = 5; */
        if (message.accelYMps2 !== 0)
            writer.tag(5, WireType.Bit64).double(message.accelYMps2);
        /* double accel_z_mps2 = 6; */
        if (message.accelZMps2 !== 0)
            writer.tag(6, WireType.Bit64).double(message.accelZMps2);
        /* double gyro_x_rad_per_s = 7; */
        if (message.gyroXRadPerS !== 0)
            writer.tag(7, WireType.Bit64).double(message.gyroXRadPerS);
        /* double gyro_y_rad_per_s = 8; */
        if (message.gyroYRadPerS !== 0)
            writer.tag(8, WireType.Bit64).double(message.gyroYRadPerS);
        /* double gyro_z_rad_per_s = 9; */
        if (message.gyroZRadPerS !== 0)
            writer.tag(9, WireType.Bit64).double(message.gyroZRadPerS);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.ImuData
 */
export const ImuData = new ImuData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GpsData$Type extends MessageType<GpsData> {
    constructor() {
        super("star.v1.GpsData", [
            { no: 1, name: "latitude_deg", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 2, name: "longitude_deg", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 3, name: "altitude_m", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 4, name: "accuracy_m", kind: "scalar", T: 1 /*ScalarType.DOUBLE*/ },
            { no: 5, name: "satellites", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "fix_type", kind: "enum", T: () => ["star.v1.GpsFix", GpsFix] }
        ]);
    }
    create(value?: PartialMessage<GpsData>): GpsData {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.latitudeDeg = 0;
        message.longitudeDeg = 0;
        message.altitudeM = 0;
        message.accuracyM = 0;
        message.satellites = 0;
        message.fixType = 0;
        if (value !== undefined)
            reflectionMergePartial<GpsData>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GpsData): GpsData {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* double latitude_deg */ 1:
                    message.latitudeDeg = reader.double();
                    break;
                case /* double longitude_deg */ 2:
                    message.longitudeDeg = reader.double();
                    break;
                case /* double altitude_m */ 3:
                    message.altitudeM = reader.double();
                    break;
                case /* double accuracy_m */ 4:
                    message.accuracyM = reader.double();
                    break;
                case /* int32 satellites */ 5:
                    message.satellites = reader.int32();
                    break;
                case /* star.v1.GpsFix fix_type */ 6:
                    message.fixType = reader.int32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GpsData, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* double latitude_deg = 1; */
        if (message.latitudeDeg !== 0)
            writer.tag(1, WireType.Bit64).double(message.latitudeDeg);
        /* double longitude_deg = 2; */
        if (message.longitudeDeg !== 0)
            writer.tag(2, WireType.Bit64).double(message.longitudeDeg);
        /* double altitude_m = 3; */
        if (message.altitudeM !== 0)
            writer.tag(3, WireType.Bit64).double(message.altitudeM);
        /* double accuracy_m = 4; */
        if (message.accuracyM !== 0)
            writer.tag(4, WireType.Bit64).double(message.accuracyM);
        /* int32 satellites = 5; */
        if (message.satellites !== 0)
            writer.tag(5, WireType.Varint).int32(message.satellites);
        /* star.v1.GpsFix fix_type = 6; */
        if (message.fixType !== 0)
            writer.tag(6, WireType.Varint).int32(message.fixType);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.GpsData
 */
export const GpsData = new GpsData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class SystemStatus$Type extends MessageType<SystemStatus> {
    constructor() {
        super("star.v1.SystemStatus", [
            { no: 1, name: "connection_status", kind: "enum", T: () => ["star.v1.ConnectionStatus", ConnectionStatus, "CONNECTION_STATUS_"] },
            { no: 2, name: "mode", kind: "enum", T: () => ["star.v1.RobotMode", RobotMode, "ROBOT_MODE_"] },
            { no: 3, name: "esp32_connected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 4, name: "lidar_connected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 5, name: "ros_connected", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "firmware_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 7, name: "uptime_s", kind: "scalar", T: 4 /*ScalarType.UINT64*/ },
            { no: 8, name: "free_heap_bytes", kind: "scalar", T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<SystemStatus>): SystemStatus {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.connectionStatus = 0;
        message.mode = 0;
        message.esp32Connected = false;
        message.lidarConnected = false;
        message.rosConnected = false;
        message.firmwareVersion = "";
        message.uptimeS = "0";
        message.freeHeapBytes = 0;
        if (value !== undefined)
            reflectionMergePartial<SystemStatus>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: SystemStatus): SystemStatus {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* star.v1.ConnectionStatus connection_status */ 1:
                    message.connectionStatus = reader.int32();
                    break;
                case /* star.v1.RobotMode mode */ 2:
                    message.mode = reader.int32();
                    break;
                case /* bool esp32_connected */ 3:
                    message.esp32Connected = reader.bool();
                    break;
                case /* bool lidar_connected */ 4:
                    message.lidarConnected = reader.bool();
                    break;
                case /* bool ros_connected */ 5:
                    message.rosConnected = reader.bool();
                    break;
                case /* string firmware_version */ 6:
                    message.firmwareVersion = reader.string();
                    break;
                case /* uint64 uptime_s */ 7:
                    message.uptimeS = reader.uint64().toString();
                    break;
                case /* uint32 free_heap_bytes */ 8:
                    message.freeHeapBytes = reader.uint32();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: SystemStatus, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* star.v1.ConnectionStatus connection_status = 1; */
        if (message.connectionStatus !== 0)
            writer.tag(1, WireType.Varint).int32(message.connectionStatus);
        /* star.v1.RobotMode mode = 2; */
        if (message.mode !== 0)
            writer.tag(2, WireType.Varint).int32(message.mode);
        /* bool esp32_connected = 3; */
        if (message.esp32Connected !== false)
            writer.tag(3, WireType.Varint).bool(message.esp32Connected);
        /* bool lidar_connected = 4; */
        if (message.lidarConnected !== false)
            writer.tag(4, WireType.Varint).bool(message.lidarConnected);
        /* bool ros_connected = 5; */
        if (message.rosConnected !== false)
            writer.tag(5, WireType.Varint).bool(message.rosConnected);
        /* string firmware_version = 6; */
        if (message.firmwareVersion !== "")
            writer.tag(6, WireType.LengthDelimited).string(message.firmwareVersion);
        /* uint64 uptime_s = 7; */
        if (message.uptimeS !== "0")
            writer.tag(7, WireType.Varint).uint64(message.uptimeS);
        /* uint32 free_heap_bytes = 8; */
        if (message.freeHeapBytes !== 0)
            writer.tag(8, WireType.Varint).uint32(message.freeHeapBytes);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message star.v1.SystemStatus
 */
export const SystemStatus = new SystemStatus$Type();
/**
 * @generated ServiceType for protobuf service star.v1.TelemetryService
 */
export const TelemetryService = new ServiceType("star.v1.TelemetryService", [
    { name: "GetTelemetry", options: {}, I: GetTelemetryRequest, O: GetTelemetryResponse },
    { name: "StreamTelemetry", serverStreaming: true, options: {}, I: StreamTelemetryRequest, O: TelemetryData },
    { name: "GetSystemStatus", options: {}, I: GetSystemStatusRequest, O: GetSystemStatusResponse }
]);
