idf_component_register(
    SRCS
        "src/star_bus_async.c"
        "src/star_bus_batch.c"
        "src/star_bus_config.c"
        "src/star_bus_debug.c"
        "src/star_bus_devices.c"
        "src/star_bus_gpio.c"
        "src/star_bus_helpers.c"
        "src/star_bus_i2c.c"
        "src/star_bus_i2c_dma.c"
        "src/star_bus_i2c_peripheral.c"
        "src/star_bus_manager.c"
        "src/star_bus_onewire.c"
        "src/star_bus_onewire_peripheral.c"
        "src/star_bus_smbus.c"
        "src/star_bus_smbus_peripheral.c"
        "src/star_bus_spi.c"
        "src/star_bus_spi_dma.c"
        "src/star_bus_spi_peripheral.c"
        "src/star_bus_stats.c"
        "src/star_bus_types.c"
        "src/star_bus_uart.c"
    INCLUDE_DIRS "include"
    REQUIRES
        driver
        esp_common
        esp_timer
        freertos
        star_core
)
