name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
          args: --property,qodana.compile.commands=build/compile_commands.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2021385077 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
