name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          submodules: recursive

      - name: Prepare C++ Analysis
        run: |
          # Create a build directory
          mkdir -p build
          
          # 1. Generate the map (paths will be wrong for Docker)
          cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -S star-rx72n-firmware -B build
          
          # 2. Fix the paths: Replace GitHub workspace path with Qodana's internal path
          #    This changes "/home/runner/work/..." to "/data/project/..."
          sed -i "s|${{ github.workspace }}|/data/project|g" build/compile_commands.json

      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2025.2
        with:
          pr-mode: false
          args: --property,qodana.compile.commands=build/compile_commands.json
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_2021385077 }}
          QODANA_ENDPOINT: 'https://qodana.cloud'
